import { createContext, useContext, useEffect, useMemo, useState } from 'react';

const LANGUAGE_STORAGE_KEY = 'athenea.language';
const DEFAULT_LANGUAGE = 'en';

const translations = {
  es: {
    'Dashboard': 'Tablero',
    'Projects': 'Proyectos',
    'Intelligence': 'Inteligencia',
    'Workstreams': 'Áreas de Trabajo',
    'Workstream': 'Área de Trabajo',
    'Areas': 'Áreas',
    'Task Management': 'Gestión de Tareas',
    'Notes': 'Notas',
    'Personal Notes': 'Notas Personales',
    'Your quick notes and ideas.': 'Tus notas e ideas rápidas.',
    'New Note': 'Nueva Nota',
    'Edit Note': 'Editar Nota',
    'Search notes...': 'Buscar notas...',
    'All': 'Todas',
    'No notes found.': 'No se encontraron notas.',
    'No notes yet. Create your first note!': '¡No hay notas aún. Crea tu primera nota!',
    'Pin note': 'Fijar nota',
    'Edit': 'Editar',
    'Delete': 'Eliminar',
    'Delete this note?': '¿Eliminar esta nota?',
    'Title': 'Título',
    'Content': 'Contenido',
    'Color': 'Color',
    'Tags': 'Etiquetas',
    'Enter note title': 'Ingresa el título de la nota',
    'Write your note...': 'Escribe tu nota...',
    'Cancel': 'Cancelar',
    'Save': 'Guardar',
    'Lead': 'Responsable',
    'Assign Lead': 'Asignar Responsable',
    'No lead assigned': 'Sin responsable asignado',
    'Assigned Lead': 'Responsable asignado',
    'Command Center': 'Centro Personal',
    'Quick Stats': 'Resumen Rápido',
    'Pending Audits': 'Auditorías Pendientes',
    'Attention Required': 'Atención Requerida',
    'Operational': 'Operativo',
    'Management': 'Gestion',
    'Add Project': 'Agregar Proyecto',
    'Audit Alerts': 'Alertas de Auditoria',
    'Resolve': 'Resolver',
    'View Details': 'Ver Detalle',
    'Worker': 'Yo',
    'Unassigned': 'Sin asignar',
    'No audit details': 'Sin detalles de auditoria',
    'No pending audits.': 'No hay alertas pendientes.',
    'Incident Report': 'Reporte de Incidencia',
    'Context': 'Contexto',
    'Date/Time': 'Fecha/Hora',
    'Conflict': 'Conflicto',
    'Failed Question': 'Pregunta fallida',
    'Answer': 'Respuesta',
    'Resolution Log': 'Registro de resolucion',
    'Resolved By': 'Resuelto por',
    'Resolved At': 'Resuelto en',
    'Resolution Note': 'Nota de resolucion',
    'Unresolved': 'Sin resolver',
    'No answer recorded': 'Sin respuesta registrada',
    'Audit not found': 'Auditoria no encontrada',
    'Unknown': 'Desconocido',
    'Report ID': 'ID de reporte',
    'Print Report': 'Imprimir Reporte',
    'Organization Logo': 'Logo de la organizacion',
    'Generated automatically by ATHENEA - Operational Governance System': 'Generado automaticamente por ATHENEA - Sistema de Gobernanza Operativa',
    'Media & Evidence': 'Evidencia y soporte',
    'No evidence attached.': 'Sin evidencia adjunta.',
    'Evidence': 'Evidencia',
    'Worker Note': 'Nota del operador',
    'Workstream not found': 'Workstream no encontrado',
    'Fleet': 'Gestión de Tareas',
    'Settings': 'Configuracion',
    'Identity & Governance': 'Identidad y Gobernanza',
    'My Profile': 'Mi Perfil',
    'My Tasks': 'Mis Tareas',
    'Assigned to you': 'Asignadas a ti',
    'No tasks assigned.': 'No tienes tareas asignadas.',
    'Operation Status': 'Estado Operativo',
    'Role Toggle': 'Cambiar Rol',
    'Login': 'Ingresar',
    'Register': 'Registrar',
    'Create & Continue': 'Crear y continuar',
    'Welcome back': 'Bienvenido de nuevo',
    'Create your operator profile': 'Crea tu perfil operativo',
    'Already have access?': 'Ya tienes acceso?',
    'Need an account?': 'Necesitas una cuenta?',
    'Sign in': 'Ingresar',
    'Build your Organization': 'Crea tu Organizacion',
    'Join with Invite Code': 'Unete con Codigo de Invitacion',
    'Onboarding': 'Onboarding',
    'Build your Organization': 'Crea tu Organizacion',
    'Complete three steps to unlock operations.': 'Completa tres pasos para activar operaciones.',
    'Identity': 'Identidad',
    'Company Name': 'Nombre de la empresa',
    'Industry': 'Industria',
    'Logo Upload': 'Subir logo',
    'Subscription': 'Suscripcion',
    'Workers': 'Usuario',
    'Workstreams': 'Áreas de Trabajo',
    'Unlimited': 'Ilimitado',
    'First Team': 'Primer Equipo',
    'Add Workstream': 'Agregar Workstream',
    'Finish Setup': 'Finalizar',
    'Add at least one workstream to continue.': 'Agrega al menos un workstream para continuar.',
    'Create at least one workstream to unlock the queue.': 'Crea al menos un workstream para habilitar la cola.',
    'Upgrade to add more workstreams.': 'Actualiza para agregar mas workstreams.',
    'Upgrade to add more workers.': 'Actualiza para agregar mas operadores.',
    'Command-ready onboarding for tactical teams.': 'Onboarding listo para equipos tacticos.',
    'Launch a new organization or join an active tenant in seconds.': 'Lanza una nueva organizacion o unete a un tenant activo en segundos.',
    'Choose a path or sign in below.': 'Elige un camino o inicia sesion abajo.',
    'Registration Wizard': 'Asistente de Registro',
    'Create your organization': 'Crea tu organizacion',
    'Complete three steps to unlock ATHENEA.': 'Completa tres pasos para activar ATHENEA.',
    'Choose your path': 'Elige tu camino',
    'Register as Business': 'Registrarse como Empresa',
    'Join as Individual': 'Unirse como Individuo',
    'Join as User': 'Unirse como Usuario',
    'I want to manage my team and operations.': 'Quiero gestionar mi equipo y operaciones.',
    'I have an invite code or my company already uses ATHENEA.': 'Tengo un codigo de invitacion o mi empresa ya usa ATHENEA.',
    'I need to join an existing ATHENEA team.': 'Necesito unirme a un equipo existente de ATHENEA.',
    'Create your user': 'Crea tu usuario',
    'Complete your profile to continue.': 'Completa tu perfil para continuar.',
    'Create user': 'Crear usuario',
    'Account': 'Cuenta',
    'Organization': 'Espacio Personal',
    'Organization Name': 'Nombre del Espacio',
    'Admin Contact': 'Contacto administrativo',
    'Invite Code': 'Codigo de invitacion',
    'Enter invite code': 'Ingresa el codigo de invitacion',
    'First Name': 'Nombre',
    'Last Name': 'Apellido',
    'Enter your name': 'Ingresa tu nombre',
    'Enter your last name': 'Ingresa tu apellido',
    'Recommended': 'Recomendado',
    'Worker limit': 'Limite de operadores',
    'Current Plan': 'Plan actual',
    'Fixed Monthly Total': 'Total mensual fijo',
    'Billing': 'Facturacion',
    'Upgrade Required': 'Actualizacion requerida',
    'ATHENEA Field Ops': 'ATHENEA Operaciones de Campo',
    'Enter your email': 'Ingresa tu correo',
    'Enter your password': 'Ingresa tu contrasena',
    'Or continue with email': 'O continua con correo',
    'Or sign in with email': 'O inicia sesion con correo',
    'Or continue with': 'O continua con',
    'Tactical Engineering System': 'Sistema de Ingeniería Táctica',
    'Ready onboarding for tactical teams.': 'Onboarding listo para equipos tácticos.',
    'Launch a new organization or join an active tenant in seconds.': 'Lanza una nueva organización o únete a un tenant activo en segundos.',
    'Register as Company': 'Registrarse como Empresa',
    'Register as User': 'Registrarse como Usuario',
    'Create your Organization': 'Crea tu Organización',
    'Complete dashboard with real-time metrics for all your active projects': 'Dashboard completo con métricas en tiempo real de todos tus proyectos activos',
    'Manage multiple teams, assign roles and granular permissions per project': 'Gestiona múltiples equipos, asigna roles y permisos granulares por proyecto',
    'Point-by-point production tracking with automatic progress reports': 'Seguimiento de producción punto por punto con reportes de avance automáticos',
    'Full inventory control with low stock alerts and transfers between projects': 'Control total de inventario con alertas de stock bajo y transferencias entre proyectos',
    'Complete audits with change history and traceability of every decision': 'Auditorías completas con historial de cambios y trazabilidad de cada decisión',
    'Automatic PDF report generation and data export for analysis': 'Generación automática de reportes PDF y exportación de datos para análisis',
    'Intelligent notification system to keep your team synchronized': 'Sistema de notificaciones inteligente para mantener a tu equipo sincronizado',
    'Instantly access your assigned task list prioritized by urgency': 'Accede instantáneamente a tu lista de tareas asignadas priorizadas por urgencia',
    'Report progress from the field with photos, GPS coordinates and voice notes': 'Reporta avances desde campo con fotos, coordenadas GPS y notas de voz',
    'Receive real-time notifications when critical tasks are assigned to you': 'Recibe notificaciones en tiempo real cuando te asignen nuevas tareas críticas',
    'Consult blueprints, diagrams and technical specs from any device': 'Consulta planos, diagramas y especificaciones técnicas desde cualquier dispositivo',
    'Collaborate with your team through integrated chat and synchronized updates': 'Colabora con tu equipo mediante chat integrado y actualizaciones sincronizadas',
    'Automatically log hours worked with progress tracking': 'Registra horas trabajadas automáticamente con seguimiento de progreso',
    'Visualize the impact of your work on overall project progress': 'Visualiza el impacto de tu trabajo en el progreso global del proyecto',
    'Continue with Google': 'Continuar con Google',
    'Continue with GitHub': 'Continuar con GitHub',
    'Continue with Apple': 'Continuar con Apple',
    'Continue with Microsoft': 'Continuar con Microsoft',
    'Logging in...': 'Iniciando sesión...',
    'Demo mode: any email and password works.': 'Modo demo: cualquier correo y contraseña funcionan.',
    'Company': 'Empresa',
    'User': 'Usuario',
    'Create your account': 'Crea tu cuenta',
    'Choose your registration type below': 'Elige tu tipo de registro',
    'Company Name': 'Nombre de Empresa',
    'Enter your company name': 'Ingresa el nombre de tu empresa',
    'Optional admin contact email': 'Correo de contacto administrativo opcional',
    'Enter invite code if you have one': 'Ingresa código de invitación si tienes uno',
    'Optional': 'Opcional',
    'Please fill all required fields': 'Por favor completa todos los campos requeridos',
    'Registration failed. Please try again.': 'Registro fallido. Por favor intenta de nuevo.',
    'Creating account...': 'Creando cuenta...',
    'Create Company Account': 'Crear Cuenta de Empresa',
    'Create User Account': 'Crear Cuenta de Usuario',
    'Already have an account?': '¿Ya tienes una cuenta?',
    'Continue to Plan Selection': 'Continuar a Selección de Plan',
    'Select your Plan': 'Selecciona tu Plan',
    'Choose the plan that fits your organization': 'Elige el plan que se ajuste a tu organización',
    'Continue to Payment': 'Continuar al Pago',
    'Payment Information': 'Información de Pago',
    'Secure payment powered by Stripe': 'Pago seguro con Stripe',
    'Plan': 'Plan',
    'Total': 'Total',
    'Cardholder Name': 'Nombre del Titular',
    'John Doe': 'Juan Pérez',
    'Card Number': 'Número de Tarjeta',
    'Expiry Date': 'Fecha de Expiración',
    'CVC': 'CVC',
    'Your payment information is encrypted and secure': 'Tu información de pago está encriptada y segura',
    'Back': 'Atrás',
    'Complete Registration': 'Completar Registro',
    'Processing...': 'Procesando...',
    'Please select a plan': 'Por favor selecciona un plan',
    'Please fill all payment fields': 'Por favor completa todos los campos de pago',
    'Up to 10 people': 'Hasta 10 personas',
    'Up to 50 people': 'Hasta 50 personas',
    'Up to 200 people': 'Hasta 200 personas',
    'Unlimited people': 'Personas ilimitadas',
    'Core Audit Engine': 'Motor de Auditoría Central',
    '2 Active Workstreams': '2 Workstreams Activos',
    'Pending Queue': 'Cola Pendiente',
    'Metrics Dashboard': 'Dashboard de Métricas',
    'Manager Roles': 'Roles de Manager',
    'Advanced Reports': 'Reportes Avanzados',
    'AI Intelligence': 'Inteligencia IA',
    '24/7 Support': 'Soporte 24/7',
    'Starter': 'Inicial',
    'Business': 'Negocios',
    'Corporate': 'Corporativo',
    'Enterprise': 'Empresarial',
    'Rules': 'Reglas',
    'Require Manager Approval': 'Requiere aprobacion del Manager',
    'Allow Worker Self-Assign': 'Permitir auto-asignacion del Operador',
    'Strict Dispatch': 'Despacho estricto',
    'Rules update instantly for this workstream.': 'Las reglas se actualizan al instante para este workstream.',
    'Pending Queue': 'Cola Pendiente',
    'Pending approval': 'Pendiente de aprobacion',
    'Awaiting approval': 'En espera de aprobacion',
    'Approve & Assign': 'Aprobar y asignar',
    'Access Restricted': 'Acceso Restringido',
    'This area is reserved for your role.': 'Esta area esta reservada para tu rol.',
    'Return to Dashboard': 'Volver al Tablero',
    'Create the first workstream to unlock this module.': 'Crea el primer workstream para habilitar este modulo.',
    'Admin': 'Administrador',
    'Manager': 'Manager',
    'Worker': 'Operador',
    'Create Workstream': 'Crear Workstream',
    'View Projects': 'Ver Proyectos',
    'Workstream name': 'Nombre del workstream',
    'Enter workstream name': 'Ingresa el nombre del workstream',
    'Workstream *': 'Workstream *',
    'Select a workstream': 'Selecciona un workstream',
    'Workstream is required': 'El workstream es requerido',
    'Workstream locked to project.': 'El workstream esta bloqueado al proyecto.',
    'Workstream:': 'Workstream:',
    'Create': 'Crear',
    'No workstreams configured yet.': 'No hay workstreams configurados.',
    'Create the first workstream to unlock analytics.': 'Crea el primer workstream para habilitar analiticas.',
    'Route to team': 'Enviar a equipo',
    'Select team': 'Seleccionar equipo',
    'Role': 'Rol',
    'My Teams': 'Mis Equipos',
    'No teams assigned.': 'No tienes equipos asignados.',
    'My Organizations': 'Mis Organizaciones',
    'Switch': 'Cambiar',
    'No organizations joined.': 'No hay organizaciones asignadas.',
    'Company Settings': 'Configuracion de Empresa',
    'Company name': 'Nombre de la empresa',
    'Brand color': 'Color de marca',
    'Logo URL': 'URL del logo',
    'Save branding': 'Guardar branding',
    'Organizations': 'Organizaciones',
    'Security & Team': 'Seguridad y Equipo',
    'Security & Roster': 'Seguridad y Roster',
    'Invite System': 'Sistema de Invitaciones',
    'Invite email': 'Correo de invitacion',
    'Send Invite': 'Enviar invitacion',
    'Expires': 'Expira',
    'No active invites.': 'No hay invitaciones activas.',
    'Tenant Roster': 'Roster del Tenant',
    'Expel from Tenant': 'Expulsar del Tenant',
    'Expel': 'Expulsar',
    'Protected': 'Protegido',
    'No members in this tenant.': 'No hay miembros en este tenant.',
    'Access revoked. Contact your administrator to regain entry.': 'Acceso revocado. Contacta a tu administrador para recuperar acceso.',
    'Tenant': 'Tenant',
    'Active tenant:': 'Tenant activo:',
    'Manage operational workstreams and defaults.': 'Gestiona workstreams y valores por defecto.',
    'Manage Workstreams': 'Gestionar Workstreams',
    'Manage organization governance and defaults.': 'Gestiona la gobernanza de la organizacion y valores por defecto.',
    'Organization Admin': 'Administracion de Organizacion',
    'Organization name': 'Nombre de organizacion',
    'Update name': 'Actualizar nombre',
    'Invite code': 'Codigo de invitacion',
    'Save invite code': 'Guardar codigo',
    'Generate code': 'Generar codigo',
    'Revoke code': 'Revocar codigo',
    'Role Escalations': 'Escalaciones de rol',
    'Engineer': 'Ingeniero',
    'Sales': 'Ventas',
    'Role Override (Testing)': 'Override de Rol (Testing)',
    'Active Role': 'Rol Activo',
    'Use current role': 'Usar rol actual',
    'Developer': 'Desarrollador',
    'Manager': 'Manager',
    'Guest': 'Invitado',
    'Clear override': 'Limpiar override',
    'New Task': 'Nueva Tarea',
    'Create a project to log tasks.': 'Crea un proyecto para registrar tareas.',
    'Create a workstream project to log tasks.': 'Crea un proyecto dentro de un workstream para registrar tareas.',
    'No active projects available. Create a project before logging tasks.': 'No hay proyectos activos disponibles. Crea un proyecto antes de registrar tareas.',
    'No active projects available. Create a workstream project before logging tasks.': 'No hay proyectos activos disponibles. Crea un proyecto dentro de un workstream antes de registrar tareas.',
    'Cancelled projects cannot receive new tasks.': 'Los proyectos cancelados no pueden recibir nuevas tareas.',
    'Tenant:': 'Tenant:',
    'Logout': 'Cerrar Sesion',
    'Field Reports': 'Reportes de Campo',
    'Service and sales intake for non-technical requests.': 'Ingreso de servicio y ventas para solicitudes no tecnicas.',
    'Support Ticket Intake': 'Ingreso de Tickets de Soporte',
    'Ticket Title': 'Titulo del Ticket',
    'Short summary': 'Resumen corto',
    'Project': 'Proyecto',
    'Select project': 'Seleccionar proyecto',
    'Category': 'Categoria',
    'Bug': 'Bug',
    'Feature Request': 'Solicitud de Feature',
    'Client Update': 'Actualizacion de Cliente',
    'Priority': 'Prioridad',
    'Low': 'Baja',
    'Mid': 'Media',
    'High': 'Alta',
    'Status': 'Estado',
    'Open': 'Abierto',
    'In Review': 'En Revision',
    'Approved': 'Aprobado',
    'Context, requested changes, or client impact': 'Contexto, cambios solicitados o impacto al cliente',
    'Submit Ticket': 'Enviar Ticket',
    'Ticket routed to ATHENEA.': 'Ticket enviado a ATHENEA.',
    'Create a project before submitting tickets.': 'Crea un proyecto antes de enviar tickets.',
    'Gatekeeper Intake': 'Ingreso Gatekeeper',
    'Active': 'Activo',
    'Inactive': 'Inactivo',
    'Step': 'Paso',
    'of': 'de',
    'Close': 'Cerrar',
    'Associate this task with a project.': 'Asocia esta tarea a un proyecto.',
    'Select at least one area.': 'Selecciona al menos un area.',
    'Task Title': 'Titulo de la Tarea',
    'Enter a concise task title': 'Ingresa un titulo conciso',
    'Add context and constraints': 'Agrega contexto y restricciones',
    'Select the signals that apply.': 'Selecciona las senales que aplican.',
    'Priority score': 'Puntaje de prioridad',
    'Level': 'Nivel',
    'Back': 'Atras',
    'Continue': 'Continuar',
    'Saving...': 'Guardando...',
    'Save': 'Guardar',
    'Task analyzed and prioritized by ATHENEA core.': 'Tarea analizada y priorizada por ATHENEA.',
    'Is this a minor cosmetic adjustment?': 'Es un ajuste cosmetico menor?',
    'Would this be nice-to-have with low impact?': 'Seria un nice-to-have con bajo impacto?',
    'Is this a low-risk refinement with minimal urgency?': 'Es un refinamiento de bajo riesgo y minima urgencia?',
    'Does this improve clarity without changing outcomes?': 'Mejora la claridad sin cambiar resultados?',
    'Is the benefit mostly cosmetic or aesthetic?': 'El beneficio es mayormente cosmetico o estetico?',
    'Is this optional for the current delivery cycle?': 'Es opcional para el ciclo actual de entrega?',
    'Is this a minor cleanup with no dependencies?': 'Es una limpieza menor sin dependencias?',
    'Would delaying this have negligible impact?': 'Retrasarlo tendria impacto despreciable?',
    'Is this a low-visibility improvement?': 'Es una mejora de baja visibilidad?',
    'Is this a small convenience enhancement?': 'Es una mejora pequena de conveniencia?',
    'Does this remove a small friction point for the team?': 'Elimina un pequeno punto de friccion para el equipo?',
    'Is this a modest efficiency gain?': 'Es una ganancia modesta de eficiencia?',
    'Will this reduce minor rework later?': 'Reduce retrabajo menor mas adelante?',
    'Is this helpful but not time-critical?': 'Es util pero no critico en tiempo?',
    'Does this improve day-to-day flow slightly?': 'Mejora ligeramente el flujo diario?',
    'Is this a small quality-of-life upgrade?': 'Es una mejora pequena de calidad de vida?',
    'Would this reduce minor confusion for operators?': 'Reduciria confusiones menores para operadores?',
    'Is this beneficial but not blocking anything?': 'Es beneficioso pero no bloquea nada?',
    'Does this prevent small errors or misclicks?': 'Previene pequenos errores o misclicks?',
    'Is this a low-priority enhancement?': 'Es una mejora de baja prioridad?',
    'Does this reduce context switching for the team?': 'Reduce el cambio de contexto del equipo?',
    'Will this improve handoffs between roles?': 'Mejora los handoffs entre roles?',
    'Is this part of the next sprint scope?': 'Es parte del alcance del proximo sprint?',
    'Does this prevent recurring low-level issues?': 'Previene issues recurrentes de bajo nivel?',
    'Will this increase operator confidence?': 'Aumenta la confianza del operador?',
    'Is this a standardization improvement?': 'Es una mejora de estandarizacion?',
    'Does this improve visibility of task status?': 'Mejora la visibilidad del estado de tareas?',
    'Will this reduce rework across teams?': 'Reduce retrabajo entre equipos?',
    'Is this a moderate efficiency gain?': 'Es una ganancia moderada de eficiencia?',
    'Is this a moderate user experience lift?': 'Es una mejora moderada de experiencia de usuario?',
    'Does this unlock progress for multiple tasks?': 'Desbloquea progreso para multiples tareas?',
    'Will this remove a recurring operational blocker?': 'Elimina un bloqueador operativo recurrente?',
    'Is this required for a committed delivery?': 'Es requerido para una entrega comprometida?',
    'Will this materially improve team throughput?': 'Mejora de forma material el throughput del equipo?',
    'Does this improve system reliability?': 'Mejora la confiabilidad del sistema?',
    'Is this needed to avoid known escalations?': 'Se necesita para evitar escalaciones conocidas?',
    'Is this aligned with current strategic objectives?': 'Esta alineado con objetivos estrategicos actuales?',
    'Will this reduce response time for ops?': 'Reducira el tiempo de respuesta para ops?',
    'Does this increase quality for key workflows?': 'Aumenta la calidad en workflows clave?',
    'Is this necessary for a public-facing milestone?': 'Es necesario para un hito publico?',
    'Is this tied to a high-impact customer outcome?': 'Esta ligado a un resultado de alto impacto para el cliente?',
    'Will delaying this cause costly rework?': 'Retrasarlo causara retrabajo costoso?',
    'Does this reduce critical operational risk?': 'Reduce riesgo operativo critico?',
    'Is this a key dependency for a delivery window?': 'Es una dependencia clave para una ventana de entrega?',
    'Does this stabilize a sensitive subsystem?': 'Estabiliza un subsistema sensible?',
    'Will this protect a contractual commitment?': 'Protege un compromiso contractual?',
    'Does this prevent high-severity incidents?': 'Previene incidentes de alta severidad?',
    'Is this required to maintain compliance?': 'Es requerido para mantener compliance?',
    'Will this unlock major productivity gains?': 'Desbloquea ganancias mayores de productividad?',
    'Is this critical to maintain service quality?': 'Es critico para mantener calidad de servicio?',
    'Is there a hard deadline within 48 hours?': 'Hay un deadline duro dentro de 48 horas?',
    'Is this blocking delivery of a committed outcome?': 'Esta bloqueando la entrega de un resultado comprometido?',
    'Would delay create significant operational exposure?': 'Retrasarlo crearia exposicion operativa significativa?',
    'Is this required to unblock a critical milestone?': 'Es requerido para desbloquear un hito critico?',
    'Will this mitigate an active incident?': 'Mitiga un incidente activo?',
    'Is this a top-level executive priority?': 'Es una prioridad ejecutiva de alto nivel?',
    'Does this prevent a high-cost escalation?': 'Previene una escalacion de alto costo?',
    'Is this essential to avoid outage risk?': 'Es esencial para evitar riesgo de outage?',
    'Will this unblock multiple dependent teams?': 'Desbloquea multiples equipos dependientes?',
    'Is this tied to a critical compliance deadline?': 'Esta ligado a un deadline critico de compliance?',
    'Is this an emergency blocking the core operation?': 'Es una emergencia que bloquea la operacion central?',
    'Is the business at immediate risk if delayed?': 'El negocio esta en riesgo inmediato si se retrasa?',
    'Is this required to restore mission-critical service?': 'Es requerido para restaurar servicio critico?',
    'Would delay cause major contractual breach?': 'Retrasarlo causaria un incumplimiento contractual mayor?',
    'Is this the top system stability priority?': 'Es la prioridad maxima de estabilidad del sistema?',
    'Is there immediate safety or compliance exposure?': 'Hay exposicion inmediata de seguridad o compliance?',
    'Is this a mission-critical customer demand?': 'Es una demanda critica del cliente?',
    'Is this blocking all downstream work right now?': 'Esta bloqueando todo el trabajo downstream ahora?',
    'Would delay cause significant financial loss?': 'Retrasarlo causaria perdida financiera significativa?',
    'Is this required to prevent system outage?': 'Es requerido para prevenir un outage del sistema?',
    'Operational tasks organized by priority level.': 'Tareas operativas organizadas por prioridad.',
    'No tasks in this bucket.': 'No hay tareas en este bucket.',
    'External Requests': 'Solicitudes Externas',
    'No field reports logged.': 'No hay reportes de campo.',
    'Active Projects': 'Proyectos Activos',
    'Active Workstreams': 'Workstreams Activos',
    'Active Projects Short': 'Proyectos Activos',
    'Completed Short': 'Finalizados',
    'Lead Command Center': 'Centro de Comando del Lider',
    'No active projects.': 'No hay proyectos activos.',
    'Active': 'Activo',
    'Empty': 'Vacio',
    'Only the Workstream Lead or Admin can manage projects here.': 'Solo el Lider del Workstream o un Admin puede gestionar proyectos aqui.',
    'Projects': 'Proyectos',
    'Operational programs aligned to ATHENEA build objectives.': 'Programas operativos alineados a objetivos ATHENEA.',
    'You do not have permission to create projects.': 'No tienes permiso para crear proyectos.',
    'New Project': 'Nuevo Proyecto',
    'Task List': 'Lista de Tareas',
    'Client:': 'Cliente:',
    'Location:': 'Ubicacion:',
    'Start Date:': 'Fecha de Inicio:',
    'Completion Date:': 'Fecha de Entrega:',
    'Maintenance:': 'Mantenimiento:',
    'Progress': 'Progreso',
    'Task progress:': 'Progreso de tareas:',
    'completed': 'completadas',
    'No projects yet': 'Aun no hay proyectos',
    'Create your first project': 'Crea tu primer proyecto',
    'Cancelled Projects': 'Proyectos Cancelados',
    'Cancelled on': 'Cancelado el',
    'Show Cancelled': 'Mostrar Cancelados',
    'Hide Cancelled': 'Ocultar Cancelados',
    'No cancelled projects.': 'No hay proyectos cancelados.',
    'Cancel': 'Cancelar',
    'Delete': 'Eliminar',
    'Restore': 'Restaurar',
    'Project not found': 'Proyecto no encontrado',
    'Back': 'Atras',
    'Back to Projects': 'Volver a Proyectos',
    'Project Information': 'Informacion del Proyecto',
    'Delivery Date': 'Fecha de Entrega',
    'Subscription': 'Suscripcion',
    'Not subscribed': 'No suscrito',
    'TBD': 'Por definir',
    'Progress': 'Progreso',
    'Total Tasks': 'Total Tareas',
    'Completed': 'Completadas',
    'Remaining': 'Pendientes',
    'Deleted': 'Eliminadas',
    'Strategic Task List': 'Lista de Tareas Estrategicas',
    'Aligned to ATHENEA priority doctrine.': 'Alineado a la doctrina de prioridad ATHENEA.',
    'Search tasks': 'Buscar tareas',
    'No tasks found for this project.': 'No hay tareas para este proyecto.',
    'Complete': 'Completar',
    'In Progress': 'En Progreso',
    'Backlog': 'Backlog',
    'Deleted Tasks': 'Tareas Eliminadas',
    'total': 'total',
    'No deleted tasks.': 'No hay tareas eliminadas.',
    'Project Settings': 'Configuracion del Proyecto',
    'Status': 'Estado',
    'Planning': 'Planificacion',
    'Client': 'Cliente',
    'Location': 'Ubicacion',
    'Start Date': 'Fecha de Inicio',
    'Maintenance': 'Mantenimiento',
    'Save Changes': 'Guardar Cambios',
    'Cancel': 'Cancelar',
    'Plan Notes': 'Notas del Plan',
    'Monthly maintenance': 'Mantenimiento mensual',
    'Project Settings': 'Configuracion del Proyecto',
    'Project Information': 'Informacion del Proyecto',
    'Create New Project': 'Crear Nuevo Proyecto',
    'Project Name *': 'Nombre del Proyecto *',
    'Description': 'Descripcion',
    'Assign Project Manager *': 'Asignar Project Manager *',
    'Select PM': 'Seleccionar PM',
    'Client Name *': 'Nombre del Cliente *',
    'Start Date *': 'Fecha de Inicio *',
    'Completion Date': 'Fecha de Entrega',
    'Maintenance Plan': 'Plan de Mantenimiento',
    'Site Address *': 'Direccion del Sitio *',
    'Cancel': 'Cancelar',
    'Create Project': 'Crear Proyecto',
    'Project name is required': 'El nombre del proyecto es requerido',
    'Client name is required': 'El nombre del cliente es requerido',
    'Site address is required': 'La direccion es requerida',
    'Start date is required': 'La fecha de inicio es requerida',
    'Please assign a PM': 'Asigna un PM',
    'Project created successfully.': 'Proyecto creado con exito.',
    'e.g., ATHENEA Command Expansion': 'ej., Expansion de comando ATHENEA',
    'Brief description of the project': 'Descripcion breve del proyecto',
    'e.g., ABC Corporation': 'ej., Corporacion ABC',
    'e.g., Monthly maintenance cadence': 'ej., Mantenimiento mensual',
    'e.g., 123 Main Street, New York, NY 10001': 'ej., Calle 123, Caracas, VE',
    'Inventory': 'Inventario',
    'Inventory Management': 'Gestion de Inventario',
    'Warehouse': 'Almacen',
    'Project Inventory': 'Inventario de Proyecto',
    'Add Item': 'Agregar Item',
    'Filter by Project:': 'Filtrar por Proyecto:',
    'All Projects': 'Todos los Proyectos',
    'Warehouse Items': 'Items de Almacen',
    'Project Items': 'Items de Proyecto',
    'Low Stock Alerts': 'Alertas de Bajo Stock',
    'Name': 'Nombre',
    'Email': 'Correo',
    'Category': 'Categoria',
    'Quantity': 'Cantidad',
    'Unit': 'Unidad',
    'Min Stock': 'Stock Minimo',
    'Global categories aligned to Gatekeeper intake.': 'Categorias globales alineadas al intake Gatekeeper.',
    'Role access': 'Acceso por rol',
    'View': 'Ver',
    'Action': 'Accion',
    'Management team has full read/write access across teams.': 'El equipo de gestion tiene acceso total de lectura/escritura en todos los equipos.',
    'Team Roster': 'Roster del equipo',
    'Search members': 'Buscar miembros',
    'Add to team': 'Agregar al equipo',
    'Remove': 'Quitar',
    'No team members assigned.': 'No hay miembros asignados.',
    'Select an organization to manage workstreams.': 'Selecciona una organizacion para gestionar workstreams.',
    'No workstreams are enabled yet.': 'No hay workstreams habilitados.',
    'Manage Workstreams': 'Gestionar Workstreams',
    'Dispatch active operators and balance workload distribution.': 'Despacha operadores activos y equilibra la carga.',
    'Team View': 'Vista de Equipos',
    'Load heatmap': 'Mapa de carga',
    'Backlog': 'Backlog',
    'Assigned': 'Asignadas',
    'Load Score': 'Indice de carga',
    'Critical tasks': 'Tareas criticas',
    'Assigned tasks': 'Tareas asignadas',
    'No assigned tasks': 'Sin tareas asignadas',
    'Team Backlog': 'Backlog del equipo',
    'Assign to Member': 'Asignar a miembro',
    'Select member': 'Seleccionar miembro',
    'No tasks for this team.': 'No hay tareas para este equipo.',
    'Locked to member': 'Bloqueada a miembro',
    'Assign to': 'Asignar a',
    'Field Report': 'Reporte de Campo',
    'Project Health': 'Salud del proyecto',
    'Total tasks': 'Total de tareas',
    'No active projects for analytics.': 'No hay proyectos activos para analitica.',
    'Throughput': 'Throughput',
    'Completed vs Created': 'Completadas vs creadas',
    'No throughput data available.': 'No hay datos de throughput.',
    'No active members for this organization.': 'No hay miembros activos para esta organizacion.',
    'e.g., ATHENEA-2026': 'ej., ATHENEA-2026',
    'Actions': 'Acciones',
    'N/A': 'N/D',
    'Edit': 'Editar',
    'Transfer': 'Transferir',
    'Add Inventory Item': 'Agregar Item de Inventario',
    'Edit Item': 'Editar Item',
    'Update': 'Actualizar',
    'Add': 'Agregar',
    'Transfer to Project': 'Transferir a Proyecto',
    'Available:': 'Disponible:',
    'Select Project': 'Seleccionar Proyecto',
    'Choose...': 'Elegir...',
    'Quantity to Transfer': 'Cantidad a Transferir',
    'Users': 'Usuarios',
    '👥 Users & Project Management': '👥 Usuarios y Gestion de Proyectos',
    '👥 Team Groups & Assignment': '👥 Grupos y Asignacion',
    'Manage all users across all projects and assign PMs.': 'Gestiona usuarios en todos los proyectos y asigna PMs.',
    'Manage users in your assigned projects.': 'Gestiona usuarios en tus proyectos asignados.',
    'Create groups and assign team members.': 'Crea grupos y asigna miembros del equipo.',
    'Add User': 'Agregar Usuario',
    'Total Users': 'Total Usuarios',
    'Pending Lead Technician Approvals': 'Aprobaciones pendientes de Lead Technician',
    'The following technicians have been proposed as Lead Technicians by supervisors. Review and approve or reject.': 'Los siguientes tecnicos fueron propuestos como Lead Technician. Revisa y aprueba o rechaza.',
    'Project:': 'Proyecto:',
    'Group:': 'Grupo:',
    'Approve': 'Aprobar',
    'Reject': 'Rechazar',
    'Search by name, email, or group...': 'Buscar por nombre, correo o grupo...',
    'All Roles': 'Todos los Roles',
    'All Status': 'Todos los Estados',
    'Active Only': 'Solo Activos',
    'Inactive Only': 'Solo Inactivos',
    'List View': 'Vista Lista',
    'Cards View': 'Vista Tarjetas',
    'Groups View': 'Vista Grupos',
    'Export to CSV': 'Exportar a CSV',
    'Export': 'Exportar',
    'selected': 'seleccionados',
    'Activate': 'Activar',
    'Deactivate': 'Desactivar',
    'Clear': 'Limpiar',
    'No users found. Try adjusting your filters.': 'No se encontraron usuarios. Ajusta los filtros.',
    'Pending Approval': 'Pendiente de Aprobacion',
    'Edit': 'Editar',
    'Delete': 'Eliminar',
    'Supervisor View:': 'Vista Supervisor:',
    'Create groups, assign Lead Techs, and distribute technicians into groups.': 'Crea grupos, asigna Lead Techs y distribuye tecnicos.',
    'Assign Group': 'Asignar Grupo',
    'Super Admin': 'Super Admin',
    'PM': 'PM',
    'Groups View:': 'Vista de Grupos:',
    'Overview of': 'Resumen de',
    'all': 'todos',
    'your': 'tus',
    'teams organized by project and group. Monitor team structure and assignments.': 'equipos organizados por proyecto y grupo. Monitorea estructura y asignaciones.',
    'Group': 'Grupo',
    '(Unassigned)': '(Sin asignar)',
    'Lead Tech:': 'Lead Tech:',
    'Technicians:': 'Tecnicos:',
    'No technicians assigned': 'No hay tecnicos asignados',
    'Supervisor Groups View:': 'Vista Grupos Supervisor:',
    'Organize teams by project and group. Assign Lead Techs and technicians.': 'Organiza equipos por proyecto y grupo. Asigna Lead Techs y tecnicos.',
    'Edit User': 'Editar Usuario',
    'Add User': 'Agregar Usuario',
    'Project Assignment': 'Asignacion de Proyecto',
    'No projects available': 'No hay proyectos disponibles',
    'Optional for Admin — assign if you want to scope admin actions to a project.': 'Opcional para Admin — asigna si quieres limitar acciones por proyecto.',
    'Group ID': 'ID de Grupo',
    '(Lead will manage this group)': '(Lead gestionara este grupo)',
    '(Assign to group)': '(Asignar a grupo)',
    'e.g., Group-A, Team-1': 'ej., Grupo-A, Equipo-1',
    'This Lead Tech will distribute tasks to technicians in this group.': 'Este Lead Tech distribuira tareas a tecnicos del grupo.',
    'Assign this technician to a group for task distribution.': 'Asigna este tecnico a un grupo para distribucion de tareas.',
    'You can only assign users to your own projects.': 'Solo puedes asignar usuarios a tus proyectos.',
    'Cannot delete Super Admin.': 'No se puede eliminar Super Admin.',
    'You do not have permission to delete this user.': 'No tienes permiso para eliminar este usuario.',
    'Delete this user?': 'Eliminar este usuario?',
    'Role:': 'Rol:',
    'Notifications': 'Notificaciones',
    'Critical task alerts and operational signals.': 'Alertas criticas y senales operativas.',
    'No critical alerts at this time.': 'No hay alertas criticas en este momento.',
    'Profile': 'Perfil',
    'User Profile': 'Perfil de Usuario',
    'Access credentials and role configuration.': 'Credenciales de acceso y configuracion de rol.',
    'User': 'Usuario',
    'Operator': 'Operador',
    'Role': 'Rol',
    'Tenant': 'Tenant',
    'Primary': 'Primary',
    'Field Reports Intake': 'Ingreso de Reportes de Campo',
    'Submit Field Report': 'Enviar Reporte de Campo',
    'System Health': 'Salud del Sistema',
    'Priority analytics and tactical system health.': 'Analitica de prioridad y salud del sistema.',
    'Tactical Analytics Loading': 'Analitica tactica cargando',
    'Fleet Readiness Loading': 'Alistamiento de flota cargando',
    'Under Maintenance': 'En mantenimiento',
    'Priority Trends': 'Tendencias de Prioridad',
    'Stable': 'Estable',
    'Elevated': 'Elevado',
    'Degraded': 'Degradado',
    'Workstreams Overview': 'Resumen de Workstreams',
    'Global categories aligned to Gatekeeper intake.': 'Categorias globales alineadas a Gatekeeper.',
    'Active': 'Activo',
    'Inactive': 'Inactivo',
    'Category ID:': 'ID de Categoria:',
    'Fleet Readiness': 'Listo de Flota',
    'Active operators and current workload distribution.': 'Operadores activos y distribucion de carga.',
    'Active Load': 'Carga Activa',
    'User Profile': 'Perfil de Usuario',
    'Login': 'Ingresar',
    'Email': 'Correo',
    'Password': 'Clave',
    'Sign In': 'Iniciar Sesion',
    'Tactical Engineering System': 'Sistema de Ingenieria Tactica',
    'Enter your email': 'Ingresa tu correo',
    'Enter your password': 'Ingresa tu clave',
    'Logging in...': 'Ingresando...',
    'Demo: Enter any email and password to login': 'Demo: Ingresa cualquier correo y clave',
    'Continue with Google': 'Continuar con Google',
    'Continue with GitHub': 'Continuar con GitHub',
    'Or continue with email': 'O continuar con correo',
    'Awaiting Command': 'Esperando Comando',
    'Enter your Company Invite Code to unlock operations.': 'Ingresa el codigo de invitacion de tu compania para desbloquear operaciones.',
    'Company Invite Code': 'Codigo de Invitacion',
    'Authorize Access': 'Autorizar Acceso',
    'Invalid invite code': 'Codigo de invitacion invalido',
    'Membership active. Select an organization to proceed.': 'Membresia activa. Selecciona una organizacion para continuar.',
    'Organization': 'Organizacion',
    'Select organization': 'Seleccionar organizacion',
    'Points': 'Puntos',
    'Production Tracking': 'Tracking de Produccion',
    'Home': 'Inicio',
    'Welcome to ATHENEA': 'Bienvenido a ATHENEA',
    'Demo': 'Demo',
    'Link to:': 'Link a:',
    'Open file ./store.js to see the global store that contains and updates the list of colors': 'Abre ./store.js para ver el store global y la lista de colores',
    'Change Color': 'Cambiar Color',
    'Back home': 'Volver al inicio',
    'Todo:': 'Tarea:',
    'Point not found': 'Punto no encontrado',
    'Go Back': 'Volver',
    'Are you sure you want to delete this point?': 'Seguro que quieres eliminar este punto?',
    'Delete Point': 'Eliminar Punto',
    'General Information': 'Informacion General',
    'Point Number:': 'Numero de Punto:',
    'Type:': 'Tipo:',
    'Category:': 'Categoria:',
    'Status:': 'Estado:',
    'X Coordinate:': 'Coordenada X:',
    'Y Coordinate:': 'Coordenada Y:',
    'Update Status': 'Actualizar Estado',
    'Pending': 'Pendiente',
    'Settings': 'Configuracion',
    'English': 'EN',
    'Spanish': 'ES',
    'Work Areas Overview': 'Resumen de Áreas de Trabajo',
    'Your tasks organized by priority level.': 'Tus tareas organizadas por nivel de prioridad.',
    'Operational tasks organized by priority level.': 'Tareas operativas organizadas por nivel de prioridad.',
    'No tasks in this bucket.': 'No hay tareas en este nivel.',
    'External Requests': 'Solicitudes Externas',
    'No field reports logged.': 'No hay reportes de campo registrados.',
    'Active Projects Short': 'Activos',
    'Completed Short': 'Completados',
    'No projects yet': 'No hay proyectos aún',
    'Active': 'Activo',
    'Empty': 'Vacío',
    'Work Areas': 'Áreas de Trabajo',
    'Organize your projects by area or category.': 'Organiza tus proyectos por área o categoría.',
    'Create Work Area': 'Crear Área de Trabajo',
    'Area name': 'Nombre del área',
    'Enter area name': 'Ingresa el nombre del área',
    'No work areas configured yet.': 'No hay áreas de trabajo configuradas aún.',
    'Area ID:': 'ID del área:',
    'Delete': 'Eliminar',
    'Remove': 'Eliminar',
    'Save': 'Guardar'
  }
};

const LanguageContext = createContext({
  language: DEFAULT_LANGUAGE,
  setLanguage: () => {},
  toggleLanguage: () => {},
  t: (key) => key
});

const getStoredLanguage = () => {
  if (typeof window === 'undefined') return DEFAULT_LANGUAGE;
  try {
    const stored = window.localStorage.getItem(LANGUAGE_STORAGE_KEY);
    return stored === 'en' || stored === 'es' ? stored : DEFAULT_LANGUAGE;
  } catch (error) {
    return DEFAULT_LANGUAGE;
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(getStoredLanguage);

  useEffect(() => {
    if (typeof window === 'undefined') return;
    try {
      window.localStorage.setItem(LANGUAGE_STORAGE_KEY, language);
    } catch (error) {
      // Ignore storage errors.
    }
  }, [language]);

  const value = useMemo(() => {
    const dictionary = translations[language] || {};
    const t = (key) => dictionary[key] || key;
    const toggleLanguage = () => setLanguage((prev) => (prev === 'es' ? 'en' : 'es'));
    return { language, setLanguage, toggleLanguage, t };
  }, [language]);

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
