import { createContext, useContext, useEffect, useMemo, useState } from 'react';

const LANGUAGE_STORAGE_KEY = 'athenea.language';
const DEFAULT_LANGUAGE = 'en';

const translations = {
  es: {
    'Dashboard': 'Tablero',
    'Projects': 'Proyectos',
    'Intelligence': 'Inteligencia',
    'Workstreams': 'Áreas de Trabajo',
    'Workstream': 'Área de Trabajo',
    'Areas': 'Áreas',
    'Task Management': 'Gestión de Tareas',
    'Work': 'Laboral',
    'Personal': 'Personal',
    'Finance': 'Finanzas',
    'Work Hub': 'Centro Laboral',
    'Personal Hub': 'Centro Personal',
    'Finance Hub': 'Centro Financiero',
    'Everything related to your daily programming work.': 'Todo lo relacionado a tu trabajo diario de programacion.',
    'Capture and organize your personal workflow.': 'Captura y organiza tu flujo personal.',
    'Keep your finances clear and predictable.': 'Mantiene tus finanzas claras y predecibles.',
    'Go to Projects': 'Ir a Proyectos',
    'Go to My Tasks': 'Ir a Mis Tareas',
    'Go to Areas': 'Ir a Areas',
    'Go to Task Management': 'Ir a Gestion de Tareas',
    'Latest Tasks': 'Ultimas tareas',

    'Go to Notes': 'Ir a Notas',
    'Go to Todos': 'Ir a Pendientes',
    'Go to Calendar': 'Ir a Calendario',
    'Pending Todos': 'Pendientes activos',
    'Go to Payments': 'Ir a Pagos',
    'Historial': 'Historial',
    'Metas': 'Metas',
    'Budgeting': 'Presupuestacion',
    'Saldo Libre': 'Saldo Libre',
    'Health Score': 'Puntaje de salud',
    'Total entries': 'Total de registros',
    'Recent entries': 'Entradas recientes',
    'No finance history entries yet.': 'Sin entradas financieras aun.',
    'Unified finance action history from aiMemory.': 'Historial financiero unificado desde aiMemory.',
    'Ritmo Sugerido': 'Ritmo Sugerido',
    'Ritmo Sugerido Diario': 'Ritmo Sugerido Diario',
    'day': 'dia',
    'Financial goals and suggested pace for the rest of the month.': 'Metas financieras y ritmo sugerido para el resto del mes.',
    'Metas por categoria': 'Metas por categoria',
    'No budgeting categories yet.': 'Aun no hay categorias presupuestarias.',
    'Compromisos Proximos': 'Compromisos Proximos',
    'Budget allocation overview by category.': 'Vista general de asignacion de presupuesto por categoria.',
    'Budget by category': 'Presupuesto por categoria',
    'Seguimiento': 'Seguimiento',
    'Planeación': 'Planeación',
    'bp.stepIncome': 'Ingresos',
    'bp.stepFixed': 'Gastos Fijos',
    'bp.stepPlan': 'Plan y Resultado',
    'bp.incomeTitle': 'Configura tus Ingresos',
    'bp.amount': 'Monto',
    'bp.frequency': 'Frecuencia',
    'bp.freqWeekly': 'Semanal',
    'bp.freqMonthly': 'Mensual',
    'bp.freqYearly': 'Anual',
    'bp.freqSpecific': 'Días específicos',
    'bp.specificDays': 'Días de cobro (separados por coma)',
    'bp.specificDaysHint': 'Ej: 1, 15',
    'bp.currency': 'Moneda',
    'bp.monthlyEstimate': 'Estimado mensual:',
    'bp.continue': 'Continuar',
    'bp.back': 'Atrás',
    'bp.fixedTitle': 'Gastos Fijos Mensuales',
    'bp.expenseName': 'Nombre del gasto',
    'bp.addExpense': 'Agregar gasto',
    'bp.totalFixed': 'Total gastos fijos:',
    'bp.available': 'Disponible tras gastos fijos:',
    'bp.planTitle': 'Elige tu Plan de Distribución',
    'bp.resultTitle': 'Resultado del Plan',
    'bp.plan': 'Plan',
    'bp.monthlyIncome': 'Ingreso mensual',
    'bp.distributed': 'Distribuido',
    'bp.unassigned': 'Sin asignar',
    'bp.fixed': 'Gastos Fijos',
    'bp.recreation': 'Recreación',
    'bp.savings': 'Ahorro',
    'bp.remaining': 'Restante',
    'bp.realExpenses': 'Gastos reales',
    'bp.canSpend': 'Puedes gastar más',
    'bp.exceeding': 'Excediendo en',
    'bp.reset': 'Reiniciar plan',
    'bp.flexible': 'Flexible',
    'bp.flexibleDesc': 'Tú decides cuánto va a recreación y ahorro.',
    'bp.moderate': 'Moderado',
    'bp.moderateDesc': '60% gastos, 25% recreación, 15% ahorro.',
    'bp.saver': 'Ahorrador',
    'bp.saverDesc': '40% gastos, 30% recreación, 30% ahorro.',
    'bp.conservative': 'Conservador',
    'bp.conservativeDesc': '70% gastos, 20% recreación, 10% ahorro.',
    'bp.ambitious': 'Ambicioso',
    'bp.ambitiousDesc': '45% gastos, 25% recreación, 30% ahorro.',
    'bp.balanced': 'Equilibrado',
    'bp.balancedDesc': 'Un tercio exacto para cada categoría.',
    'bp.monthCycleTitle': 'Ciclo Mensual del Presupuesto',
    'bp.cycleDay': 'Día de corte mensual',
    'bp.currentMonth': 'Mes actual:',
    'bp.nextBudgetDate': 'Fecha de renovación',
    'bp.monthStatus': 'Estado del mes:',
    'bp.statusApplied': 'Aplicado',
    'bp.statusPending': 'Pendiente',
    'bp.prevCarryOver': 'Arrastre del mes anterior:',
    'bp.effectiveIncome': 'Ingreso efectivo del mes:',
    'bp.pendingMonthSetup': 'Jarvis: este mes aún no tiene presupuesto aplicado. Completa los pasos y aplica tu presupuesto mensual.',
    'bp.applyMonthBudget': 'Aplicar presupuesto del mes',
    'bp.updateMonthBudget': 'Actualizar presupuesto del mes',
    'bp.monthHistory': 'Historial mensual de presupuestos',
    'bp.noMonthHistory': 'Aún no hay presupuestos mensuales aplicados.',
    'Ingresos': 'Ingresos',
      'Egresos': 'Egresos',
      'month': 'mes',
      'months': 'meses',
      'Agente': 'Agente',
      'All agents': 'Todos los agentes',
      'Movimientos': 'Movimientos',
      'Add Transaction': 'Agregar Transaccion',
      'Save Transaction': 'Guardar Transaccion',
      'Date': 'Fecha',
      'Source of Truth — all financial movements feed Budgeting, Hub and Calendar.': 'Fuente de verdad — todos los movimientos alimentan Budgeting, Hub y Calendario.',
      'Add Goal': 'Agregar Meta',
      'Goal name': 'Nombre de la meta',
      'Target Amount': 'Monto Objetivo',
      'Monthly Contribution': 'Aporte Mensual',
      'Goal category': 'Categoria de la meta',
      'Target date': 'Fecha objetivo',
      'Save Goal': 'Guardar Meta',
      'Mis Metas': 'Mis Metas',
      'No goals yet. Add your first financial goal.': 'Sin metas aun. Agrega tu primera meta financiera.',
      'Finance Summary': 'Resumen Financiero',
      'Pending Commitments': 'Compromisos Pendientes',
      'Financial Activity': 'Actividad Financiera',
      'movements': 'movimientos',
      'Agent Log': 'Registro de Agentes',
      'Fecha de Logro': 'Fecha de Logro',
      'Meta Completada': 'Meta Completada',
      'Ahorros Comprometidos': 'Ahorros Comprometidos',
      'Saldo Libre supera tus compromisos — considera aumentar tu aporte mensual.': 'Saldo Libre supera tus compromisos — considera aumentar tu aporte mensual.',
      'Total Budget': 'Presupuesto Total',
      'Categories at risk': 'Categorias en riesgo',
      'Limit': 'Limite',
      'Recent Budget Alerts': 'Alertas de Presupuesto Recientes',
      'Cancelar': 'Cancelar',
    'Upcoming Payments': 'Pagos proximos',
    "Today's Focus": 'Enfoque de hoy',
    'Upcoming Reminders': 'Recordatorios proximos',
    'Next 7 days': 'Proximos 7 dias',
    'Monthly Total': 'Total mensual',
    'Recurring Payments': 'Pagos recurrentes',
    'Weekly Progress': 'Progreso semanal',
    'Daily Routines': 'Rutinas diarias',
    'New routine': 'Nueva rutina',
    'No routines yet.': 'No hay rutinas aun.',
    'Mark': 'Marcar',
    'Add': 'Agregar',
    'Monthly Budget': 'Presupuesto mensual',
    'Monthly History': 'Historial mensual',
    'Spent': 'Gastado',
    'Add Category': 'Agregar categoria',
    'Category name': 'Nombre de categoria',
    'Monthly limit': 'Limite mensual',
    'Add Expense': 'Agregar gasto',
    'Select category': 'Selecciona categoria',
    'Categories': 'Categorias',
    'No categories yet.': 'No hay categorias aun.',
    'Recent Expenses': 'Gastos recientes',
    'No expenses yet.': 'No hay gastos aun.',
    'Expense': 'Gasto',
    'Notes': 'Notas',
    'Personal Notes': 'Notas Personales',
    'Your quick notes and ideas.': 'Tus notas e ideas rápidas.',
    'New Note': 'Nueva Nota',
    'Edit Note': 'Editar Nota',
    'Search notes...': 'Buscar notas...',
    'All': 'Todas',
    'No notes found.': 'No se encontraron notas.',
    'No notes yet. Create your first note!': '¡No hay notas aún. Crea tu primera nota!',
    'Pin note': 'Fijar nota',
    'Edit': 'Editar',
    'Delete': 'Eliminar',
    'Delete this note?': '¿Eliminar esta nota?',
    'Title': 'Título',
    'Content': 'Contenido',
    'Color': 'Color',
    'Tags': 'Etiquetas',
    'Enter note title': 'Ingresa el título de la nota',
    'Write your note...': 'Escribe tu nota...',
    'Cancel': 'Cancelar',
    'Save': 'Guardar',
    'Recent Notes': 'Notas Recientes',
    'View more': 'Ver mas',
    'View all notes': 'Ver todas las notas',
    'No notes yet.': 'No hay notas aun.',

    'Capture everything. Sort later.': 'Captura todo. Ordena despues.',
    'Note': 'Nota',
    'Todo': 'Pendiente',
    'Todos': 'Pendientes',
    'Payment': 'Pago',
    'Payments': 'Pagos',
    'Add Note': 'Agregar Nota',
    'Add Todo': 'Agregar Pendiente',
    'Add Payment': 'Agregar Pago',
    'Todo List': 'Lista de Pendientes',
    'Track your progress in small steps.': 'Sigue tu progreso en pasos pequenos.',
    'What needs to be done?': 'Que hay que hacer?',
    'Todo title': 'Titulo del pendiente',
    'Due Date': 'Fecha limite',
    'Priority': 'Prioridad',
    'Low': 'Baja',
    'Normal': 'Normal',
    'High': 'Alta',
    'Progress': 'Progreso',
    'Done': 'Hecho',
    'Reopen': 'Reabrir',
    'No todos yet.': 'No hay pendientes aun.',
    'Delete this todo?': 'Eliminar este pendiente?',
    'Track recurring and upcoming payments.': 'Controla pagos recurrentes y proximos.',
    'Payment name': 'Nombre del pago',
    'Rent, subscription, invoice...': 'Renta, suscripcion, factura...',
    'Amount': 'Monto',
    'Currency': 'Moneda',
    'Frequency': 'Frecuencia',
    'Next Due Date': 'Proxima fecha',
    'Weekly': 'Semanal',
    'Monthly': 'Mensual',
    'Yearly': 'Anual',
    'Mark paid': 'Marcar pagado',
    'No payments yet.': 'No hay pagos aun.',
    'Delete this payment?': 'Eliminar este pago?',
    'Untitled Note': 'Nota sin titulo',
    'Untitled Todo': 'Pendiente sin titulo',
    'Untitled Payment': 'Pago sin titulo',
    'Untitled': 'Sin titulo',
    'Note title': 'Titulo de la nota',
    'Optional details': 'Detalles opcionales',
    'Reminders': 'Recordatorios',
    'No upcoming reminders.': 'No hay recordatorios proximos.',
    'Due today': 'Vence hoy',
    'Overdue': 'Vencido',
    'View': 'Ver',
    'Upcoming reminders': 'Recordatorios proximos',
    'Critical alerts': 'Alertas criticas',
    'Critical task alerts and reminders.': 'Alertas criticas y recordatorios.',
    'In 1 day': 'En 1 dia',
    'In 3 days': 'En 3 dias',
    'In 7 days': 'En 7 dias',
    'Reminder': 'Recordatorio',
    'Payment due': 'Pago por vencer',
    'Todo due': 'Pendiente por vencer',
    'Note reminder': 'Recordatorio de nota',
    'Open': 'Abrir',
    'Dismiss': 'Descartar',
      'Calendar': 'Calendario',
      'Manage your events, deadlines, and reminders.': 'Gestiona tus eventos, fechas límite y recordatorios.',
      'New Event': 'Nuevo Evento',
      'Edit Event': 'Editar Evento',
      'Delete this event?': '¿Eliminar este evento?',
      'Today': 'Hoy',
      'Today\'s Events': 'Eventos de Hoy',
      'Event': 'Evento',
      'Deadline': 'Fecha Límite',
      'Meeting': 'Reunión',
      'Event title': 'Título del evento',
      'Event description': 'Descripción del evento',
      'Description': 'Descripción',
      'Type': 'Tipo',
      'All day': 'Todo el día',
      'Start Date': 'Fecha de Inicio',
      'End Date': 'Fecha de Fin',
      'Reminder Date': 'Fecha de Recordatorio',
      'optional': 'opcional',
      'Will appear in your calendar': 'Aparecerá en tu calendario',
      'more': 'más',
      'Sun': 'Dom',
      'Mon': 'Lun',
      'Tue': 'Mar',
      'Wed': 'Mié',
      'Thu': 'Jue',
      'Fri': 'Vie',
      'Sat': 'Sáb',
      'January': 'Enero',
      'February': 'Febrero',
      'March': 'Marzo',
      'April': 'Abril',
      'May': 'Mayo',
      'June': 'Junio',
      'July': 'Julio',
      'August': 'Agosto',
      'September': 'Septiembre',
      'October': 'Octubre',
      'November': 'Noviembre',
      'December': 'Diciembre',
    'Lead': 'Responsable',
    'Assign Lead': 'Asignar Responsable',
    'No lead assigned': 'Sin responsable asignado',
    'Assigned Lead': 'Responsable asignado',
    'Command Center': 'Centro Personal',
    'Quick Stats': 'Resumen Rápido',
    'Pending Audits': 'Auditorías Pendientes',
    'Attention Required': 'Atención Requerida',
    'Operational': 'Operativo',
    'Management': 'Gestion',
    'Add Project': 'Agregar Proyecto',
    'Audit Alerts': 'Alertas de Auditoria',
    'Resolve': 'Resolver',
    'View Details': 'Ver Detalle',
    'Worker': 'Yo',
    'Unassigned': 'Sin asignar',
    'No audit details': 'Sin detalles de auditoria',
    'No pending audits.': 'No hay alertas pendientes.',
    'Incident Report': 'Reporte de Incidencia',
    'Context': 'Contexto',
    'Date/Time': 'Fecha/Hora',
    'Conflict': 'Conflicto',
    'Failed Question': 'Pregunta fallida',
    'Answer': 'Respuesta',
    'Resolution Log': 'Registro de resolucion',
    'Resolved By': 'Resuelto por',
    'Resolved At': 'Resuelto en',
    'Resolution Note': 'Nota de resolucion',
    'Unresolved': 'Sin resolver',
    'No answer recorded': 'Sin respuesta registrada',
    'Audit not found': 'Auditoria no encontrada',
    'Unknown': 'Desconocido',
    'Report ID': 'ID de reporte',
    'Print Report': 'Imprimir Reporte',
    'Organization Logo': 'Logo de la organizacion',
    'Generated automatically by ATHENEA - Operational Governance System': 'Generado automaticamente por ATHENEA - Sistema de Gobernanza Operativa',
    'Media & Evidence': 'Evidencia y soporte',
    'No evidence attached.': 'Sin evidencia adjunta.',
    'Evidence': 'Evidencia',
    'Worker Note': 'Nota del operador',
    'Workstream not found': 'Workstream no encontrado',
    'Fleet': 'Gestión de Tareas',
    'Settings': 'Configuracion',
    'Identity & Governance': 'Identidad y Gobernanza',
    'My Profile': 'Mi Perfil',
    'My Tasks': 'Mis Tareas',
    'Assigned to you': 'Asignadas a ti',
    'No tasks assigned.': 'No tienes tareas asignadas.',
    'Operation Status': 'Estado Operativo',
    'Role Toggle': 'Cambiar Rol',
    'Login': 'Ingresar',
    'Register': 'Registrar',
    'Create & Continue': 'Crear y continuar',
    'Welcome back': 'Bienvenido de nuevo',
    'Create your operator profile': 'Crea tu perfil operativo',
    'Already have access?': 'Ya tienes acceso?',
    'Need an account?': 'Necesitas una cuenta?',
    'Sign in': 'Ingresar',
    'Build your Organization': 'Crea tu Organizacion',
    'Join with Invite Code': 'Unete con Codigo de Invitacion',
    'Onboarding': 'Onboarding',
    'Complete three steps to unlock operations.': 'Completa tres pasos para activar operaciones.',
    'Identity': 'Identidad',
    'Company Name': 'Nombre de la empresa',
    'Industry': 'Industria',
    'Logo Upload': 'Subir logo',
    'Subscription': 'Suscripcion',
    'Workers': 'Usuario',
    'Unlimited': 'Ilimitado',
    'First Team': 'Primer Equipo',
    'Add Workstream': 'Agregar Workstream',
    'Finish Setup': 'Finalizar',
    'Add at least one workstream to continue.': 'Agrega al menos un workstream para continuar.',
    'Create at least one workstream to unlock the queue.': 'Crea al menos un workstream para habilitar la cola.',
    'Upgrade to add more workstreams.': 'Actualiza para agregar mas workstreams.',
    'Upgrade to add more workers.': 'Actualiza para agregar mas operadores.',
    'Command-ready onboarding for tactical teams.': 'Onboarding listo para equipos tacticos.',
    'Launch a new organization or join an active tenant in seconds.': 'Lanza una nueva organizacion o unete a un tenant activo en segundos.',
    'Choose a path or sign in below.': 'Elige un camino o inicia sesion abajo.',
    'Registration Wizard': 'Asistente de Registro',
    'Create your organization': 'Crea tu organizacion',
    'Complete three steps to unlock ATHENEA.': 'Completa tres pasos para activar ATHENEA.',
    'Choose your path': 'Elige tu camino',
    'Register as Business': 'Registrarse como Empresa',
    'Join as Individual': 'Unirse como Individuo',
    'Join as User': 'Unirse como Usuario',
    'I want to manage my team and operations.': 'Quiero gestionar mi equipo y operaciones.',
    'I have an invite code or my company already uses ATHENEA.': 'Tengo un codigo de invitacion o mi empresa ya usa ATHENEA.',
    'I need to join an existing ATHENEA team.': 'Necesito unirme a un equipo existente de ATHENEA.',
    'Create your user': 'Crea tu usuario',
    'Complete your profile to continue.': 'Completa tu perfil para continuar.',
    'Create user': 'Crear usuario',
    'Account': 'Cuenta',
    'Organization': 'Espacio Personal',
    'Organization Name': 'Nombre del Espacio',
    'Admin Contact': 'Contacto administrativo',
    'Invite Code': 'Codigo de invitacion',
    'Enter invite code': 'Ingresa el codigo de invitacion',
    'First Name': 'Nombre',
    'Last Name': 'Apellido',
    'Enter your name': 'Ingresa tu nombre',
    'Enter your last name': 'Ingresa tu apellido',
    'Recommended': 'Recomendado',
    'Worker limit': 'Limite de operadores',
    'Current Plan': 'Plan actual',
    'Fixed Monthly Total': 'Total mensual fijo',
    'Billing': 'Facturacion',
    'Upgrade Required': 'Actualizacion requerida',
    'ATHENEA Field Ops': 'ATHENEA Operaciones de Campo',
    'Enter your email': 'Ingresa tu correo',
    'Enter your password': 'Ingresa tu contrasena',
    'Or continue with email': 'O continua con correo',
    'Or sign in with email': 'O inicia sesion con correo',
    'Or continue with': 'O continua con',
    'Personal Assistant': 'Asistente Personal',
    'Ready onboarding for tactical teams.': 'Onboarding listo para equipos tácticos.',
    'Register as Company': 'Registrarse como Empresa',
    'Register as User': 'Registrarse como Usuario',
    'Create your Organization': 'Crea tu Organización',
    'Complete dashboard with real-time metrics for all your active projects': 'Dashboard completo con métricas en tiempo real de todos tus proyectos activos',
    'Manage multiple teams, assign roles and granular permissions per project': 'Gestiona múltiples equipos, asigna roles y permisos granulares por proyecto',
    'Point-by-point production tracking with automatic progress reports': 'Seguimiento de producción punto por punto con reportes de avance automáticos',
    'Full inventory control with low stock alerts and transfers between projects': 'Control total de inventario con alertas de stock bajo y transferencias entre proyectos',
    'Complete audits with change history and traceability of every decision': 'Auditorías completas con historial de cambios y trazabilidad de cada decisión',
    'Automatic PDF report generation and data export for analysis': 'Generación automática de reportes PDF y exportación de datos para análisis',
    'Intelligent notification system to keep your team synchronized': 'Sistema de notificaciones inteligente para mantener a tu equipo sincronizado',
    'Instantly access your assigned task list prioritized by urgency': 'Accede instantáneamente a tu lista de tareas asignadas priorizadas por urgencia',
    'Report progress from the field with photos, GPS coordinates and voice notes': 'Reporta avances desde campo con fotos, coordenadas GPS y notas de voz',
    'Receive real-time notifications when critical tasks are assigned to you': 'Recibe notificaciones en tiempo real cuando te asignen nuevas tareas críticas',
    'Consult blueprints, diagrams and technical specs from any device': 'Consulta planos, diagramas y especificaciones técnicas desde cualquier dispositivo',
    'Collaborate with your team through integrated chat and synchronized updates': 'Colabora con tu equipo mediante chat integrado y actualizaciones sincronizadas',
    'Automatically log hours worked with progress tracking': 'Registra horas trabajadas automáticamente con seguimiento de progreso',
    'Visualize the impact of your work on overall project progress': 'Visualiza el impacto de tu trabajo en el progreso global del proyecto',
    'Continue with Google': 'Continuar con Google',
    'Continue with GitHub': 'Continuar con GitHub',
    'Continue with Apple': 'Continuar con Apple',
    'Continue with Microsoft': 'Continuar con Microsoft',
    'Logging in...': 'Iniciando sesión...',
    'Demo mode: any email and password works.': 'Modo demo: cualquier correo y contraseña funcionan.',
    'Company': 'Empresa',
    'User': 'Usuario',
    'Create your account': 'Crea tu cuenta',
    'Choose your registration type below': 'Elige tu tipo de registro',
    'Enter your company name': 'Ingresa el nombre de tu empresa',
    'Optional admin contact email': 'Correo de contacto administrativo opcional',
    'Enter invite code if you have one': 'Ingresa código de invitación si tienes uno',
    'Optional': 'Opcional',
    'Please fill all required fields': 'Por favor completa todos los campos requeridos',
    'Registration failed. Please try again.': 'Registro fallido. Por favor intenta de nuevo.',
    'Creating account...': 'Creando cuenta...',
    'Create Company Account': 'Crear Cuenta de Empresa',
    'Create User Account': 'Crear Cuenta de Usuario',
    'Already have an account?': '¿Ya tienes una cuenta?',
    'Continue to Plan Selection': 'Continuar a Selección de Plan',
    'Select your Plan': 'Selecciona tu Plan',
    'Choose the plan that fits your organization': 'Elige el plan que se ajuste a tu organización',
    'Continue to Payment': 'Continuar al Pago',
    'Payment Information': 'Información de Pago',
    'Secure payment powered by Stripe': 'Pago seguro con Stripe',
    'Plan': 'Plan',
    'Total': 'Total',
    'Cardholder Name': 'Nombre del Titular',
    'John Doe': 'Juan Pérez',
    'Card Number': 'Número de Tarjeta',
    'Expiry Date': 'Fecha de Expiración',
    'CVC': 'CVC',
    'Your payment information is encrypted and secure': 'Tu información de pago está encriptada y segura',
    'Back': 'Atrás',
    'Complete Registration': 'Completar Registro',
    'Processing...': 'Procesando...',
    'Please select a plan': 'Por favor selecciona un plan',
    'Please fill all payment fields': 'Por favor completa todos los campos de pago',
    'Up to 10 people': 'Hasta 10 personas',
    'Up to 50 people': 'Hasta 50 personas',
    'Up to 200 people': 'Hasta 200 personas',
    'Unlimited people': 'Personas ilimitadas',
    'Core Audit Engine': 'Motor de Auditoría Central',
    '2 Active Workstreams': '2 Workstreams Activos',
    'Pending Queue': 'Cola Pendiente',
    'Metrics Dashboard': 'Dashboard de Métricas',
    'Manager Roles': 'Roles de Manager',
    'Advanced Reports': 'Reportes Avanzados',
    'AI Intelligence': 'Inteligencia IA',
    '24/7 Support': 'Soporte 24/7',
    'Starter': 'Inicial',
    'Business': 'Negocios',
    'Corporate': 'Corporativo',
    'Enterprise': 'Empresarial',
    'Rules': 'Reglas',
    'Require Manager Approval': 'Requiere aprobacion del Manager',
    'Allow Worker Self-Assign': 'Permitir auto-asignacion del Operador',
    'Strict Dispatch': 'Despacho estricto',
    'Rules update instantly for this workstream.': 'Las reglas se actualizan al instante para este workstream.',
    'Pending approval': 'Pendiente de aprobacion',
    'Awaiting approval': 'En espera de aprobacion',
    'Approve & Assign': 'Aprobar y asignar',
    'Access Restricted': 'Acceso Restringido',
    'This area is reserved for your role.': 'Esta area esta reservada para tu rol.',
    'Return to Dashboard': 'Volver al Tablero',
    'Create the first workstream to unlock this module.': 'Crea el primer workstream para habilitar este modulo.',
    'Admin': 'Administrador',
    'Manager': 'Manager',
    'Create Workstream': 'Crear Workstream',
    'View Projects': 'Ver Proyectos',
    'Workstream name': 'Nombre del workstream',
    'Enter workstream name': 'Ingresa el nombre del workstream',
    'Workstream *': 'Workstream *',
    'Select a workstream': 'Selecciona un workstream',
    'Workstream is required': 'El workstream es requerido',
    'Workstream locked to project.': 'El workstream esta bloqueado al proyecto.',
    'Workstream:': 'Workstream:',
    'Create': 'Crear',
    'No workstreams configured yet.': 'No hay workstreams configurados.',
    'Create the first workstream to unlock analytics.': 'Crea el primer workstream para habilitar analiticas.',
    'Route to team': 'Enviar a equipo',
    'Select team': 'Seleccionar equipo',
    'Role': 'Rol',
    'My Teams': 'Mis Equipos',
    'No teams assigned.': 'No tienes equipos asignados.',
    'My Organizations': 'Mis Organizaciones',
    'Switch': 'Cambiar',
    'No organizations joined.': 'No hay organizaciones asignadas.',
    'Company Settings': 'Configuracion de Empresa',
    'Company name': 'Nombre de la empresa',
    'Brand color': 'Color de marca',
    'Logo URL': 'URL del logo',
    'Save branding': 'Guardar branding',
    'Organizations': 'Organizaciones',
    'Security & Team': 'Seguridad y Equipo',
    'Security & Roster': 'Seguridad y Roster',
    'Invite System': 'Sistema de Invitaciones',
    'Invite email': 'Correo de invitacion',
    'Send Invite': 'Enviar invitacion',
    'Expires': 'Expira',
    'No active invites.': 'No hay invitaciones activas.',
    'Tenant Roster': 'Roster del Tenant',
    'Expel from Tenant': 'Expulsar del Tenant',
    'Expel': 'Expulsar',
    'Protected': 'Protegido',
    'No members in this tenant.': 'No hay miembros en este tenant.',
    'Access revoked. Contact your administrator to regain entry.': 'Acceso revocado. Contacta a tu administrador para recuperar acceso.',
    'Tenant': 'Tenant',
    'Active tenant:': 'Tenant activo:',
    'Manage operational workstreams and defaults.': 'Gestiona workstreams y valores por defecto.',
    'Manage Workstreams': 'Gestionar Workstreams',
    'Manage organization governance and defaults.': 'Gestiona la gobernanza de la organizacion y valores por defecto.',
    'Organization Admin': 'Administracion de Organizacion',
    'Organization name': 'Nombre de organizacion',
    'Update name': 'Actualizar nombre',
    'Invite code': 'Codigo de invitacion',
    'Save invite code': 'Guardar codigo',
    'Generate code': 'Generar codigo',
    'Revoke code': 'Revocar codigo',
    'Role Escalations': 'Escalaciones de rol',
    'Engineer': 'Ingeniero',
    'Sales': 'Ventas',
    'Role Override (Testing)': 'Override de Rol (Testing)',
    'Active Role': 'Rol Activo',
    'Use current role': 'Usar rol actual',
    'Developer': 'Desarrollador',
    'Guest': 'Invitado',
    'Clear override': 'Limpiar override',
    'New Task': 'Nueva Tarea',
    'Create a project to log tasks.': 'Crea un proyecto para registrar tareas.',
    'Create a workstream project to log tasks.': 'Crea un proyecto dentro de un workstream para registrar tareas.',
    'No active projects available. Create a project before logging tasks.': 'No hay proyectos activos disponibles. Crea un proyecto antes de registrar tareas.',
    'No active projects available. Create a workstream project before logging tasks.': 'No hay proyectos activos disponibles. Crea un proyecto dentro de un workstream antes de registrar tareas.',
    'Cancelled projects cannot receive new tasks.': 'Los proyectos cancelados no pueden recibir nuevas tareas.',
    'Tenant:': 'Tenant:',
    'Logout': 'Cerrar Sesion',
    'Field Reports': 'Reportes de Campo',
    'Service and sales intake for non-technical requests.': 'Ingreso de servicio y ventas para solicitudes no tecnicas.',
    'Support Ticket Intake': 'Ingreso de Tickets de Soporte',
    'Ticket Title': 'Titulo del Ticket',
    'Short summary': 'Resumen corto',
    'Project': 'Proyecto',
    'Select project': 'Seleccionar proyecto',
    'Category': 'Categoria',
    'Bug': 'Bug',
    'Feature Request': 'Solicitud de Feature',
    'Client Update': 'Actualizacion de Cliente',
    'Mid': 'Media',
    'Status': 'Estado',
    'In Review': 'En Revision',
    'Approved': 'Aprobado',
    'Context, requested changes, or client impact': 'Contexto, cambios solicitados o impacto al cliente',
    'Submit Ticket': 'Enviar Ticket',
    'Ticket routed to ATHENEA.': 'Ticket enviado a ATHENEA.',
    'Create a project before submitting tickets.': 'Crea un proyecto antes de enviar tickets.',
    'Gatekeeper Intake': 'Ingreso Gatekeeper',
    'Active': 'Activo',
    'Inactive': 'Inactivo',
    'Step': 'Paso',
    'of': 'de',
    'Close': 'Cerrar',
    'Associate this task with a project.': 'Asocia esta tarea a un proyecto.',
    'Select at least one area.': 'Selecciona al menos un area.',
    'Task Title': 'Titulo de la Tarea',
    'Enter a concise task title': 'Ingresa un titulo conciso',
    'Add context and constraints': 'Agrega contexto y restricciones',
    'Select the signals that apply.': 'Selecciona las senales que aplican.',
    'Priority score': 'Puntaje de prioridad',
    'Level': 'Nivel',
    'Continue': 'Continuar',
    'Saving...': 'Guardando...',
    'Task analyzed and prioritized by ATHENEA core.': 'Tarea analizada y priorizada por ATHENEA.',
    'Is this a minor cosmetic adjustment?': 'Es un ajuste cosmetico menor?',
    'Would this be nice-to-have with low impact?': 'Seria un nice-to-have con bajo impacto?',
    'Is this a low-risk refinement with minimal urgency?': 'Es un refinamiento de bajo riesgo y minima urgencia?',
    'Does this improve clarity without changing outcomes?': 'Mejora la claridad sin cambiar resultados?',
    'Is the benefit mostly cosmetic or aesthetic?': 'El beneficio es mayormente cosmetico o estetico?',
    'Is this optional for the current delivery cycle?': 'Es opcional para el ciclo actual de entrega?',
    'Is this a minor cleanup with no dependencies?': 'Es una limpieza menor sin dependencias?',
    'Would delaying this have negligible impact?': 'Retrasarlo tendria impacto despreciable?',
    'Is this a low-visibility improvement?': 'Es una mejora de baja visibilidad?',
    'Is this a small convenience enhancement?': 'Es una mejora pequena de conveniencia?',
    'Does this remove a small friction point for the team?': 'Elimina un pequeno punto de friccion para el equipo?',
    'Is this a modest efficiency gain?': 'Es una ganancia modesta de eficiencia?',
    'Will this reduce minor rework later?': 'Reduce retrabajo menor mas adelante?',
    'Is this helpful but not time-critical?': 'Es util pero no critico en tiempo?',
    'Does this improve day-to-day flow slightly?': 'Mejora ligeramente el flujo diario?',
    'Is this a small quality-of-life upgrade?': 'Es una mejora pequena de calidad de vida?',
    'Would this reduce minor confusion for operators?': 'Reduciria confusiones menores para operadores?',
    'Is this beneficial but not blocking anything?': 'Es beneficioso pero no bloquea nada?',
    'Does this prevent small errors or misclicks?': 'Previene pequenos errores o misclicks?',
    'Is this a low-priority enhancement?': 'Es una mejora de baja prioridad?',
    'Does this reduce context switching for the team?': 'Reduce el cambio de contexto del equipo?',
    'Will this improve handoffs between roles?': 'Mejora los handoffs entre roles?',
    'Is this part of the next sprint scope?': 'Es parte del alcance del proximo sprint?',
    'Does this prevent recurring low-level issues?': 'Previene issues recurrentes de bajo nivel?',
    'Will this increase operator confidence?': 'Aumenta la confianza del operador?',
    'Is this a standardization improvement?': 'Es una mejora de estandarizacion?',
    'Does this improve visibility of task status?': 'Mejora la visibilidad del estado de tareas?',
    'Will this reduce rework across teams?': 'Reduce retrabajo entre equipos?',
    'Is this a moderate efficiency gain?': 'Es una ganancia moderada de eficiencia?',
    'Is this a moderate user experience lift?': 'Es una mejora moderada de experiencia de usuario?',
    'Does this unlock progress for multiple tasks?': 'Desbloquea progreso para multiples tareas?',
    'Will this remove a recurring operational blocker?': 'Elimina un bloqueador operativo recurrente?',
    'Is this required for a committed delivery?': 'Es requerido para una entrega comprometida?',
    'Will this materially improve team throughput?': 'Mejora de forma material el throughput del equipo?',
    'Does this improve system reliability?': 'Mejora la confiabilidad del sistema?',
    'Is this needed to avoid known escalations?': 'Se necesita para evitar escalaciones conocidas?',
    'Is this aligned with current strategic objectives?': 'Esta alineado con objetivos estrategicos actuales?',
    'Will this reduce response time for ops?': 'Reducira el tiempo de respuesta para ops?',
    'Does this increase quality for key workflows?': 'Aumenta la calidad en workflows clave?',
    'Is this necessary for a public-facing milestone?': 'Es necesario para un hito publico?',
    'Is this tied to a high-impact customer outcome?': 'Esta ligado a un resultado de alto impacto para el cliente?',
    'Will delaying this cause costly rework?': 'Retrasarlo causara retrabajo costoso?',
    'Does this reduce critical operational risk?': 'Reduce riesgo operativo critico?',
    'Is this a key dependency for a delivery window?': 'Es una dependencia clave para una ventana de entrega?',
    'Does this stabilize a sensitive subsystem?': 'Estabiliza un subsistema sensible?',
    'Will this protect a contractual commitment?': 'Protege un compromiso contractual?',
    'Does this prevent high-severity incidents?': 'Previene incidentes de alta severidad?',
    'Is this required to maintain compliance?': 'Es requerido para mantener compliance?',
    'Will this unlock major productivity gains?': 'Desbloquea ganancias mayores de productividad?',
    'Is this critical to maintain service quality?': 'Es critico para mantener calidad de servicio?',
    'Is there a hard deadline within 48 hours?': 'Hay un deadline duro dentro de 48 horas?',
    'Is this blocking delivery of a committed outcome?': 'Esta bloqueando la entrega de un resultado comprometido?',
    'Would delay create significant operational exposure?': 'Retrasarlo crearia exposicion operativa significativa?',
    'Is this required to unblock a critical milestone?': 'Es requerido para desbloquear un hito critico?',
    'Will this mitigate an active incident?': 'Mitiga un incidente activo?',
    'Is this a top-level executive priority?': 'Es una prioridad ejecutiva de alto nivel?',
    'Does this prevent a high-cost escalation?': 'Previene una escalacion de alto costo?',
    'Is this essential to avoid outage risk?': 'Es esencial para evitar riesgo de outage?',
    'Will this unblock multiple dependent teams?': 'Desbloquea multiples equipos dependientes?',
    'Is this tied to a critical compliance deadline?': 'Esta ligado a un deadline critico de compliance?',
    'Is this an emergency blocking the core operation?': 'Es una emergencia que bloquea la operacion central?',
    'Is the business at immediate risk if delayed?': 'El negocio esta en riesgo inmediato si se retrasa?',
    'Is this required to restore mission-critical service?': 'Es requerido para restaurar servicio critico?',
    'Would delay cause major contractual breach?': 'Retrasarlo causaria un incumplimiento contractual mayor?',
    'Is this the top system stability priority?': 'Es la prioridad maxima de estabilidad del sistema?',
    'Is there immediate safety or compliance exposure?': 'Hay exposicion inmediata de seguridad o compliance?',
    'Is this a mission-critical customer demand?': 'Es una demanda critica del cliente?',
    'Is this blocking all downstream work right now?': 'Esta bloqueando todo el trabajo downstream ahora?',
    'Would delay cause significant financial loss?': 'Retrasarlo causaria perdida financiera significativa?',
    'Is this required to prevent system outage?': 'Es requerido para prevenir un outage del sistema?',
    'Operational tasks organized by priority level.': 'Tareas operativas organizadas por prioridad.',
    'No tasks in this bucket.': 'No hay tareas en este bucket.',
    'External Requests': 'Solicitudes Externas',
    'No field reports logged.': 'No hay reportes de campo.',
    'Active Projects': 'Proyectos Activos',
    'Active Workstreams': 'Workstreams Activos',
    'Active Projects Short': 'Proyectos Activos',
    'Completed Short': 'Finalizados',
    'Lead Command Center': 'Centro de Comando del Lider',
    'No active projects.': 'No hay proyectos activos.',
    'Empty': 'Vacio',
    'Only the Workstream Lead or Admin can manage projects here.': 'Solo el Lider del Workstream o un Admin puede gestionar proyectos aqui.',
    'Operational programs aligned to ATHENEA build objectives.': 'Programas operativos alineados a objetivos ATHENEA.',
    'You do not have permission to create projects.': 'No tienes permiso para crear proyectos.',
    'New Project': 'Nuevo Proyecto',
    'Task List': 'Lista de Tareas',
    'Client:': 'Cliente:',
    'Location:': 'Ubicacion:',
    'Start Date:': 'Fecha de Inicio:',
    'Completion Date:': 'Fecha de Entrega:',
    'Maintenance:': 'Mantenimiento:',
    'Task progress:': 'Progreso de tareas:',
    'completed': 'completadas',
    'No projects yet': 'Aun no hay proyectos',
    'Create your first project': 'Crea tu primer proyecto',
    'Cancelled Projects': 'Proyectos Cancelados',
    'Cancelled on': 'Cancelado el',
    'Show Cancelled': 'Mostrar Cancelados',
    'Hide Cancelled': 'Ocultar Cancelados',
    'No cancelled projects.': 'No hay proyectos cancelados.',
    'Restore': 'Restaurar',
    'Project not found': 'Proyecto no encontrado',
    'Back to Projects': 'Volver a Proyectos',
    'Project Information': 'Informacion del Proyecto',
    'Delivery Date': 'Fecha de Entrega',
    'Not subscribed': 'No suscrito',
    'TBD': 'Por definir',
    'Total Tasks': 'Total Tareas',
    'Completed': 'Completadas',
    'Remaining': 'Pendientes',
    'Deleted': 'Eliminadas',
    'Strategic Task List': 'Lista de Tareas Estrategicas',
    'Aligned to ATHENEA priority doctrine.': 'Alineado a la doctrina de prioridad ATHENEA.',
    'Search tasks': 'Buscar tareas',
    'No tasks found for this project.': 'No hay tareas para este proyecto.',
    'Complete': 'Completar',
    'In Progress': 'En Progreso',
    'Backlog': 'Backlog',
    'Deleted Tasks': 'Tareas Eliminadas',
    'total': 'total',
    'No deleted tasks.': 'No hay tareas eliminadas.',
    'Project Settings': 'Configuracion del Proyecto',
    'Planning': 'Planificacion',
    'Client': 'Cliente',
    'Location': 'Ubicacion',
    'Maintenance': 'Mantenimiento',
    'Save Changes': 'Guardar Cambios',
    'Plan Notes': 'Notas del Plan',
    'Monthly maintenance': 'Mantenimiento mensual',
    'Create New Project': 'Crear Nuevo Proyecto',
    'Project Name *': 'Nombre del Proyecto *',
    'Assign Project Manager *': 'Asignar Project Manager *',
    'Select PM': 'Seleccionar PM',
    'Client Name *': 'Nombre del Cliente *',
    'Start Date *': 'Fecha de Inicio *',
    'Completion Date': 'Fecha de Entrega',
    'Maintenance Plan': 'Plan de Mantenimiento',
    'Site Address *': 'Direccion del Sitio *',
    'Create Project': 'Crear Proyecto',
    'Project name is required': 'El nombre del proyecto es requerido',
    'Client name is required': 'El nombre del cliente es requerido',
    'Site address is required': 'La direccion es requerida',
    'Start date is required': 'La fecha de inicio es requerida',
    'Please assign a PM': 'Asigna un PM',
    'Project created successfully.': 'Proyecto creado con exito.',
    'e.g., ATHENEA Command Expansion': 'ej., Expansion de comando ATHENEA',
    'Brief description of the project': 'Descripcion breve del proyecto',
    'e.g., ABC Corporation': 'ej., Corporacion ABC',
    'e.g., Monthly maintenance cadence': 'ej., Mantenimiento mensual',
    'e.g., 123 Main Street, New York, NY 10001': 'ej., Calle 123, Caracas, VE',
    'Inventory': 'Inventario',
    'Inventory Management': 'Gestion de Inventario',
    'Warehouse': 'Almacen',
    'Project Inventory': 'Inventario de Proyecto',
    'Add Item': 'Agregar Item',
    'Filter by Project:': 'Filtrar por Proyecto:',
    'All Projects': 'Todos los Proyectos',
    'Warehouse Items': 'Items de Almacen',
    'Project Items': 'Items de Proyecto',
    'Low Stock Alerts': 'Alertas de Bajo Stock',
    'Name': 'Nombre',
    'Email': 'Correo',
    'Quantity': 'Cantidad',
    'Unit': 'Unidad',
    'Min Stock': 'Stock Minimo',
    'Global categories aligned to Gatekeeper intake.': 'Categorias globales alineadas al intake Gatekeeper.',
    'Role access': 'Acceso por rol',
    'Management team has full read/write access across teams.': 'El equipo de gestion tiene acceso total de lectura/escritura en todos los equipos.',
    'Team Roster': 'Roster del equipo',
    'Search members': 'Buscar miembros',
    'Add to team': 'Agregar al equipo',
    'Remove': 'Quitar',
    'No team members assigned.': 'No hay miembros asignados.',
    'Select an organization to manage workstreams.': 'Selecciona una organizacion para gestionar workstreams.',
    'No workstreams are enabled yet.': 'No hay workstreams habilitados.',
    'Dispatch active operators and balance workload distribution.': 'Despacha operadores activos y equilibra la carga.',
    'Team View': 'Vista de Equipos',
    'Load heatmap': 'Mapa de carga',
    'Assigned': 'Asignadas',
    'Load Score': 'Indice de carga',
    'Critical tasks': 'Tareas criticas',
    'Assigned tasks': 'Tareas asignadas',
    'No assigned tasks': 'Sin tareas asignadas',
    'Team Backlog': 'Backlog del equipo',
    'Assign to Member': 'Asignar a miembro',
    'Select member': 'Seleccionar miembro',
    'No tasks for this team.': 'No hay tareas para este equipo.',
    'Locked to member': 'Bloqueada a miembro',
    'Assign to': 'Asignar a',
    'Field Report': 'Reporte de Campo',
    'Project Health': 'Salud del proyecto',
    'Total tasks': 'Total de tareas',
    'No active projects for analytics.': 'No hay proyectos activos para analitica.',
    'Throughput': 'Throughput',
    'Completed vs Created': 'Completadas vs creadas',
    'No throughput data available.': 'No hay datos de throughput.',
    'No active members for this organization.': 'No hay miembros activos para esta organizacion.',
    'e.g., ATHENEA-2026': 'ej., ATHENEA-2026',
    'Actions': 'Acciones',
    'N/A': 'N/D',
    'Transfer': 'Transferir',
    'Add Inventory Item': 'Agregar Item de Inventario',
    'Edit Item': 'Editar Item',
    'Update': 'Actualizar',
    'Transfer to Project': 'Transferir a Proyecto',
    'Available:': 'Disponible:',
    'Select Project': 'Seleccionar Proyecto',
    'Choose...': 'Elegir...',
    'Quantity to Transfer': 'Cantidad a Transferir',
    'Users': 'Usuarios',
    '👥 Users & Project Management': '👥 Usuarios y Gestion de Proyectos',
    '👥 Team Groups & Assignment': '👥 Grupos y Asignacion',
    'Manage all users across all projects and assign PMs.': 'Gestiona usuarios en todos los proyectos y asigna PMs.',
    'Manage users in your assigned projects.': 'Gestiona usuarios en tus proyectos asignados.',
    'Create groups and assign team members.': 'Crea grupos y asigna miembros del equipo.',
    'Add User': 'Agregar Usuario',
    'Total Users': 'Total Usuarios',
    'Pending Lead Technician Approvals': 'Aprobaciones pendientes de Lead Technician',
    'The following technicians have been proposed as Lead Technicians by supervisors. Review and approve or reject.': 'Los siguientes tecnicos fueron propuestos como Lead Technician. Revisa y aprueba o rechaza.',
    'Project:': 'Proyecto:',
    'Group:': 'Grupo:',
    'Approve': 'Aprobar',
    'Reject': 'Rechazar',
    'Search by name, email, or group...': 'Buscar por nombre, correo o grupo...',
    'All Roles': 'Todos los Roles',
    'All Status': 'Todos los Estados',
    'Active Only': 'Solo Activos',
    'Inactive Only': 'Solo Inactivos',
    'List View': 'Vista Lista',
    'Cards View': 'Vista Tarjetas',
    'Groups View': 'Vista Grupos',
    'Export to CSV': 'Exportar a CSV',
    'Export': 'Exportar',
    'selected': 'seleccionados',
    'Activate': 'Activar',
    'Deactivate': 'Desactivar',
    'Clear': 'Limpiar',
    'No users found. Try adjusting your filters.': 'No se encontraron usuarios. Ajusta los filtros.',
    'Pending Approval': 'Pendiente de Aprobacion',
    'Supervisor View:': 'Vista Supervisor:',
    'Create groups, assign Lead Techs, and distribute technicians into groups.': 'Crea grupos, asigna Lead Techs y distribuye tecnicos.',
    'Assign Group': 'Asignar Grupo',
    'Super Admin': 'Super Admin',
    'PM': 'PM',
    'Groups View:': 'Vista de Grupos:',
    'Overview of': 'Resumen de',
    'all': 'todos',
    'your': 'tus',
    'teams organized by project and group. Monitor team structure and assignments.': 'equipos organizados por proyecto y grupo. Monitorea estructura y asignaciones.',
    'Group': 'Grupo',
    '(Unassigned)': '(Sin asignar)',
    'Lead Tech:': 'Lead Tech:',
    'Technicians:': 'Tecnicos:',
    'No technicians assigned': 'No hay tecnicos asignados',
    'Supervisor Groups View:': 'Vista Grupos Supervisor:',
    'Organize teams by project and group. Assign Lead Techs and technicians.': 'Organiza equipos por proyecto y grupo. Asigna Lead Techs y tecnicos.',
    'Edit User': 'Editar Usuario',
    'Project Assignment': 'Asignacion de Proyecto',
    'No projects available': 'No hay proyectos disponibles',
    'Optional for Admin — assign if you want to scope admin actions to a project.': 'Opcional para Admin — asigna si quieres limitar acciones por proyecto.',
    'Group ID': 'ID de Grupo',
    '(Lead will manage this group)': '(Lead gestionara este grupo)',
    '(Assign to group)': '(Asignar a grupo)',
    'e.g., Group-A, Team-1': 'ej., Grupo-A, Equipo-1',
    'This Lead Tech will distribute tasks to technicians in this group.': 'Este Lead Tech distribuira tareas a tecnicos del grupo.',
    'Assign this technician to a group for task distribution.': 'Asigna este tecnico a un grupo para distribucion de tareas.',
    'You can only assign users to your own projects.': 'Solo puedes asignar usuarios a tus proyectos.',
    'Cannot delete Super Admin.': 'No se puede eliminar Super Admin.',
    'You do not have permission to delete this user.': 'No tienes permiso para eliminar este usuario.',
    'Delete this user?': 'Eliminar este usuario?',
    'Role:': 'Rol:',
    'Notifications': 'Notificaciones',
    'Critical task alerts and operational signals.': 'Alertas criticas y senales operativas.',
    'No critical alerts at this time.': 'No hay alertas criticas en este momento.',
    'Profile': 'Perfil',
    'User Profile': 'Perfil de Usuario',
    'Access credentials and role configuration.': 'Credenciales de acceso y configuracion de rol.',
    'Operator': 'Operador',
    'Primary': 'Primary',
    'Field Reports Intake': 'Ingreso de Reportes de Campo',
    'Submit Field Report': 'Enviar Reporte de Campo',
    'System Health': 'Salud del Sistema',
    'Priority analytics and tactical system health.': 'Analitica de prioridad y salud del sistema.',
    'Tactical Analytics Loading': 'Analitica tactica cargando',
    'Fleet Readiness Loading': 'Alistamiento de flota cargando',
    'Under Maintenance': 'En mantenimiento',
    'Priority Trends': 'Tendencias de Prioridad',
    'Stable': 'Estable',
    'Elevated': 'Elevado',
    'Degraded': 'Degradado',
    'No Data': 'Sin datos',
    'Workstreams Overview': 'Resumen de Workstreams',
    'Category ID:': 'ID de Categoria:',
    'Fleet Readiness': 'Listo de Flota',
    'Active operators and current workload distribution.': 'Operadores activos y distribucion de carga.',
    'Active Load': 'Carga Activa',
    'Password': 'Clave',
    'Sign In': 'Iniciar Sesion',
    'Demo: Enter any email and password to login': 'Demo: Ingresa cualquier correo y clave',
    'Awaiting Command': 'Esperando Comando',
    'Enter your Company Invite Code to unlock operations.': 'Ingresa el codigo de invitacion de tu compania para desbloquear operaciones.',
    'Company Invite Code': 'Codigo de Invitacion',
    'Authorize Access': 'Autorizar Acceso',
    'Invalid invite code': 'Codigo de invitacion invalido',
    'Membership active. Select an organization to proceed.': 'Membresia activa. Selecciona una organizacion para continuar.',
    'Select organization': 'Seleccionar organizacion',
    'Points': 'Puntos',
    'Production Tracking': 'Tracking de Produccion',
    'Home': 'Inicio',
    'Welcome to ATHENEA': 'Bienvenido a ATHENEA',
    'Demo': 'Demo',
    'Link to:': 'Link a:',
    'Open file ./store.js to see the global store that contains and updates the list of colors': 'Abre ./store.js para ver el store global y la lista de colores',
    'Change Color': 'Cambiar Color',
    'Back home': 'Volver al inicio',
    'Todo:': 'Tarea:',
    'Point not found': 'Punto no encontrado',
    'Go Back': 'Volver',
    'Are you sure you want to delete this point?': 'Seguro que quieres eliminar este punto?',
    'Delete Point': 'Eliminar Punto',
    'General Information': 'Informacion General',
    'Point Number:': 'Numero de Punto:',
    'Type:': 'Tipo:',
    'Category:': 'Categoria:',
    'Status:': 'Estado:',
    'X Coordinate:': 'Coordenada X:',
    'Y Coordinate:': 'Coordenada Y:',
    'Update Status': 'Actualizar Estado',
    'Pending': 'Pendiente',
    'English': 'EN',
    'Spanish': 'ES',
    'Work Areas Overview': 'Resumen de Áreas de Trabajo',
    'Your tasks organized by priority level.': 'Tus tareas organizadas por nivel de prioridad.',
    'Work Areas': 'Áreas de Trabajo',
    'Organize your projects by area or category.': 'Organiza tus proyectos por área o categoría.',
    'Create Work Area': 'Crear Área de Trabajo',
    'Area name': 'Nombre del área',
    'Enter area name': 'Ingresa el nombre del área',
    'No work areas configured yet.': 'No hay áreas de trabajo configuradas aún.',
    'Area ID:': 'ID del área:',
    'Collaborators': 'Colaboradores',
    'Track external collaborators and their assigned work orders.': 'Rastrea colaboradores externos y sus órdenes de trabajo asignadas.',
    'Add external collaborators to track their work and projects.': 'Agrega colaboradores externos para rastrear su trabajo y proyectos.',
    'Add Collaborator': 'Agregar Colaborador',
    'New Collaborator': 'Nuevo Colaborador',
    'No collaborators yet.': 'No hay colaboradores aún.',
    'Contact Information': 'Información de Contacto',
    'Basic Information': 'Información Básica',
    'Edit Collaborator': 'Editar Colaborador',
    'Delete this collaborator?': '¿Eliminar este colaborador?',
    'Active Orders': 'Órdenes Activas',
    'Associated Projects': 'Proyectos Asociados',
    'No projects associated': 'No hay proyectos asociados',
    'Phone': 'Teléfono',
    'Work Orders': 'Órdenes de Trabajo',
    'New Order': 'Nueva Orden',
    'No active work orders.': 'No hay órdenes de trabajo activas.',
    'No work orders yet': 'Aún no hay órdenes de trabajo',
    'Assigned to': 'Asignado a',
    'Edit Work Order': 'Editar Orden de Trabajo',
    'New Work Order': 'Nueva Orden de Trabajo',
    'Enter full name': 'Ingresa el nombre completo',
    'email@example.com': 'correo@ejemplo.com',
    'e.g., Developer, Designer': 'ej.: Desarrollador, Diseñador',
    'e.g., Frontend, Backend': 'ej.: Frontend, Backend',
    'No projects available. Create a project first.': 'No hay proyectos disponibles. Crea un proyecto primero.',
    'Enter work order title': 'Ingresa el título de la orden',
    'Describe the work to be done': 'Describe el trabajo a realizar',
    'Select project (optional)': 'Selecciona proyecto (opcional)',
    'Select collaborator': 'Seleccionar colaborador',
    'low': 'baja',
    'medium': 'media',
    'high': 'alta',
    'Go to Collaborators': 'Ir a Colaboradores',

    // ── Omnibar UI ──
    'What do you want to do?': '¿Qué quieres hacer?',
    'type your query or command': 'escribe tu consulta o comando',
    'No voice input detected': 'No se detectó entrada de voz',
    'tap here to close': 'toca aquí para cerrar',
    'Action': 'Acción',
    'Got it': 'Entendido',
    'View budget': 'Ver presupuesto',
    'Did not understand that request.': 'No entendí esa solicitud.',
    'I need some details for': 'Necesito algunos datos para',
    'First command setup': 'Configuración del primer comando',
    'Create collaborator': 'Crear colaborador',
    'Create project': 'Crear proyecto',
    'Create task': 'Crear tarea',
    'Create routine': 'Crear rutina',
    'Create reminder': 'Crear recordatorio',
    'Create note': 'Crear nota',
    'Record expense': 'Registrar gasto',
    'Record income': 'Registrar ingreso',
    'Response': 'Respuesta',
    'Financial Analysis': 'Análisis Financiero',

    // ── DailyCheckin ──────────────────────────────────────────────────
    'Daily Check-in': 'Check-in diario',
    'Mood': 'Estado de ánimo',
    'Energy': 'Energía',
    'Sleep hours': 'Horas de sueño',
    'Quick note': 'Nota rápida',
    'How are you feeling today?': '¿Cómo te sientes hoy?',
    'Save check-in': 'Guardar check-in',
    '✓ Saved': '✓ Guardado',

    // ── PersonalHub ───────────────────────────────────────────────────
    'Quick Capture': 'Captura rápida',
    'Click to edit': 'Clic para editar',
    'No routines today.': 'Sin rutinas hoy.',
    'Add Routine': 'Agregar rutina',
    'Delete routine': 'Eliminar rutina',
    'Delete this routine?': '¿Eliminar esta rutina?',
    'Open note': 'Abrir nota',

    // ── WorkHub ───────────────────────────────────────────────────────
    'Create priority task': 'Crear tarea prioritaria',
    'New task': 'Nueva tarea',
    'No tasks yet.': 'Sin tareas aún.',
    'Critical Tasks': 'Tareas críticas',

    // ── Finance ───────────────────────────────────────────────────────
    'Financial Health': 'Salud financiera',
    'Free Balance': 'Saldo libre',
    'Salud Financiera': 'Salud financiera',
    'Click to edit limit': 'Clic para editar límite',
    'Delete category and orphan its expenses?': '¿Eliminar categoría y huerfanar sus gastos?',

    // ── Navbar ────────────────────────────────────────────────────────
    'Journal': 'Diario',
    'Weekly Review': 'Revisión semanal',
    'History': 'Historial',
    'Goals': 'Metas',
    'Statistics': 'Estadísticas',

    // ── DailyStandup ──────────────────────────────────────────────────
    'Daily Standup': 'Daily Standup',
    'Standup submitted': 'Standup enviado',
    'have a productive day!': '¡que tengas un día productivo!',
    'Later': 'Después',
    'What did you do yesterday?': '¿Qué hiciste ayer?',
    'Completed tasks…': 'Tareas completadas…',
    'What will you do today?': '¿Qué harás hoy?',
    'Tasks in progress…': 'Tareas en progreso…',
    'Any blockers?': '¿Algún bloqueo?',
    'None': 'Ninguno',
    'Focus Mode': 'Modo enfoque',

    // ── SpendingCharts ────────────────────────────────────────────────
    'Spending Charts': 'Gráficas de gasto',
    'No expenses recorded yet.': 'Aún no hay gastos registrados.',
    'Other': 'Otro',

    // ── HabitTracker ──────────────────────────────────────────────────
    'Habits — last 7 days': 'Hábitos — últimos 7 días',

    // ── Finance health labels ─────────────────────────────────────────
    'Healthy': 'Saludable',
    'Attention': 'Atención',
    'Critical': 'Crítico',
    'Jarvis — Latest analysis': 'Jarvis — Último análisis',
    'Show agent diagnostics in Omnibar': 'Mostrar diagnóstico de agentes en el Omnibar',

    // ── Stats ─────────────────────────────────────────────────────────
    'Stats & Achievements': 'Estadísticas y logros',
    'Tasks Completed': 'Tareas completadas',
    'Projects Done': 'Proyectos terminados',
    'Notes Created': 'Notas creadas',
    'Day Streak': 'Días seguidos',
    'Achievements': 'Logros',
    'Detailed Statistics': 'Estadísticas detalladas',
    'Longest Streak': 'Racha más larga',
    'Todos Completed': 'Pendientes completados',
    'Tags Used': 'Etiquetas usadas',
    'Last Active': 'Última actividad',
    'Reset Stats': 'Reiniciar estadísticas',
    'Your real progress — calculated from your data.': 'Tu progreso real — calculado desde tus datos.',
    'Goals Achieved': 'Metas logradas',
    'Focus Hours': 'Horas de foco',
    'Journal Days': 'Días con journal',
    'Projects Completed': 'Proyectos completados',
    'Total Check-ins': 'Check-ins totales',
    'Average Mood': 'Humor promedio',
    'Total Focus Minutes': 'Minutos de foco totales',
    'Recorded Expenses': 'Gastos registrados',
    'Reset stats and achievements? This cannot be undone.': '¿Resetear stats y logros? No se puede deshacer.',

    // ── Login ─────────────────────────────────────────────────────────
    'What\'s your name?': '¿Cómo te llamas?',
    'Your name or alias': 'Tu nombre o alias',
    'Your personal productivity system': 'Tu sistema de productividad personal',
    'Starting...': 'Iniciando...',
    '🚀 Start': '🚀 Empezar',

    // ── IdentityHub ───────────────────────────────────────────────────
    'Identity Protocol': 'Protocolo de Identidad',
    'ATHENEA will learn who you are and how to address you': 'ATHENEA aprenderá quién eres y cómo dirigirse a ti',
    'Operator Profile': 'Perfil del Operador',
    'Good morning,': 'Buenos días,',
    'Your mission here...': 'Tu misión aquí...',
    'Title / Rank': 'Título / Rango',
    'Preferred Name': 'Nombre Preferido',
    'How ATHENEA will address you': 'Cómo ATHENEA te llamará',
    'Your name here': 'Tu nombre aquí',
    'Agent aliases': 'Forma de llamarte por agente',
    'Define how each agent calls you by origin: Jarvis (Iron Man), Cortana (Halo), SHODAN (System Shock).': 'Define cómo te llama cada agente según su origen: Jarvis (Iron Man), Cortana (Halo), SHODAN (System Shock).',
    'Mission / Current Goals': 'Misión / Objetivos Actuales',
    'Describe your current goals: savings, productivity, expansion, etc. ATHENEA will use this to prioritize advice.': 'Describe tus objetivos actuales: ahorro, productividad, expansión, etc. ATHENEA usará esto para priorizar consejos.',
    'Behavior Configuration': 'Configuración de Comportamiento',
    'Work Start Time': 'Hora de Inicio Laboral',
    'Work End Time': 'Hora de Fin Laboral',
    'Voice / Tone Protocol': 'Protocolo de Voz / Tono',
    'Select how ATHENEA should communicate with you': 'Selecciona cómo ATHENEA debe comunicarse contigo',
    'Formal & Refined': 'Formal & Refinado',
    'Efficiency, resource optimization': 'Eficiencia, optimización de recursos',
    'Tactical & Empathetic': 'Táctico & Empático',
    'Mission, wellbeing, direct connection': 'Misión, bienestar, conexión directa',
    'Operation Zones (Geofencing)': 'Zonas de Operación (Geofencing)',
    'Define coordinates for home and work. ATHENEA will know where you are.': 'Define las coordenadas de tu casa y tu trabajo. ATHENEA sabrá dónde estás.',
    'Home zone': 'Casa',
    'Work zone': 'Trabajo',
    'Latitude': 'Latitud',
    'Longitude': 'Longitud',
    'Active Protocol': 'Protocolo Activo',
    'ATHENEA will recognize': 'ATHENEA reconocerá a',
    'using protocol': 'usando el protocolo',
    'will call you': 'te dirá',
    'and': 'y',
    'Your mission of': 'Tu misión de',
    'will guide suggestions': 'guiará sus sugerencias',
    'Automatic Phone Weather': 'Clima Automático del Teléfono',
    'ATHENEA will use device location for weather automatically, no manual API key needed.': 'ATHENEA usará la ubicación del dispositivo para obtener clima automáticamente, sin API key manual.',
    'Recommended mode': 'Modo recomendado',
    'The system queries weather by phone geolocation and syncs alerts in background.': 'El sistema consulta clima por geolocalización del teléfono y sincroniza alertas en segundo plano.',
    'Active provider:': 'Proveedor activo:',
    'no manual setup': 'sin configuración manual',
    'Enable automatic weather alerts': 'Activar alertas climáticas automáticas',
    'Alert Settings': 'Configuración de Alertas',
    'Rain (hours ahead)': 'Lluvia (horas previas)',
    'Critical wind (m/s)': 'Viento crítico (m/s)',
    'Alert extreme temperatures': 'Alertar temperaturas extremas',
    '✓ Identity Saved': '✓ Identidad Guardada',
    'Save Identity': 'Guardar Identidad',

    // ── Common ────────────────────────────────────────────────────────

    // ── Settings — AI / Language ─────────────────────────────────────
    'Language': 'Idioma',
    'Interface is in English': 'La interfaz está en Español',
    'Artificial Intelligence': 'Inteligencia Artificial',
    'Configure your API key to activate Cortana, Jarvis and SHODAN with real AI.': 'Configura tu API key para activar a Cortana, Jarvis y SHODAN con IA real.',
    'Provider': 'Proveedor',
    'free': 'gratis',
    'Testing…': 'Probando…',
    'Connected': 'Conectado',
    'Retry': 'Reintentar',
    'Test connection': 'Probar conexión',
    'Groq is free. Get your key at console.groq.com': 'Groq es gratuito. Obtén tu key en console.groq.com',
    'OpenAI requires credits. Get your key at platform.openai.com': 'OpenAI requiere créditos. Obtén tu key en platform.openai.com',
    'AI configuration saved': 'Configuración de IA guardada',
    'Enter your API key first': 'Ingresa tu API key primero',
    'Connection successful — AI active': 'Conexión exitosa — IA activa',
    'invalid key': 'clave inválida',
    'Could not connect to AI provider': 'No se pudo conectar al proveedor de IA',
    'ATHENEA — personal, local and private.': 'ATHENEA — personal, local y privada.',

    // ── Settings — Debug / Backup / Danger ───────────────────────────
    'Internal tools moved outside the main Omnibar.': 'Herramientas internas movidas fuera del Omnibar principal.',
    'Simulate Bank': 'Simular Banco',
    'Refresh ActionBridge Log': 'Refrescar ActionBridge Log',
    'Data Backup & Restore': 'Respaldo y restauración de datos',
    'Export or recover full state snapshots.': 'Exporta o recupera snapshots completos del estado.',
    'Export PDF Backup': 'Exportar respaldo PDF',
    'Export JSON Backup': 'Exportar respaldo JSON',
    'Paste your backup JSON here...': 'Pega tu JSON de respaldo aquí...',
    'Import & Restore Data': 'Importar y restaurar datos',
    'Danger Zone': 'Zona de peligro',
    'Irreversible actions. Proceed with caution.': 'Acciones irreversibles. Procede con cuidado.',
    'Create Emergency Backup': 'Crear respaldo de emergencia',
    'Clear All Data (Cannot Undo!)': 'Borrar todos los datos (¡no se puede deshacer!)',

    // ── Intelligence page ────────────────────────────────────────────
    'Live Feed': 'En vivo',
    'Analytics': 'Análisis',
    'Recent Actions': 'Acciones recientes',
    'All Hubs': 'Todos los hubs',
    'All Levels': 'Todos los niveles',
    'No records yet for Work.': 'Sin registros aún para Trabajo.',
    'No records yet for Personal.': 'Sin registros aún para Personal.',
    'No records yet for Finance.': 'Sin registros aún para Finanzas.',
    'Just now': 'Ahora mismo',
    'm ago': ' min',
    'h ago': ' h',
    'd ago': ' d',
    'Medium': 'Medio',
    'Info': 'Info',

    // ── Journal autosave ─────────────────────────────────────────────
    'Saving…': 'Guardando…',
    'Saved': 'Guardado',

    // ── Calendar ─────────────────────────────────────────────────────
    'Monthly view': 'Vista mensual',
    'Agenda view': 'Vista agenda',

    // ── Color labels (Notes / Calendar) ──────────────────────────────
    'Blue': 'Azul',
    'Gold': 'Dorado',
    'Green': 'Verde',
    'Orange': 'Naranja',
    'Red': 'Rojo',
    'Purple': 'Morado',
    'Pink': 'Rosa',
    'Gray': 'Gris',

    // ── Navbar ────────────────────────────────────────────────────────
    'Switch to Spanish': 'Cambiar a Español',
    'Switch to English': 'Cambiar a Inglés',
  },
  en: {
    'Seguimiento': 'Tracking',
    'Planeación': 'Planning',
    'bp.stepIncome': 'Income',
    'bp.stepFixed': 'Fixed Expenses',
    'bp.stepPlan': 'Plan and Result',
    'bp.incomeTitle': 'Set your income',
    'bp.amount': 'Amount',
    'bp.frequency': 'Frequency',
    'bp.freqWeekly': 'Weekly',
    'bp.freqMonthly': 'Monthly',
    'bp.freqYearly': 'Yearly',
    'bp.freqSpecific': 'Specific days',
    'bp.specificDays': 'Income days (comma separated)',
    'bp.specificDaysHint': 'Example: 1, 15',
    'bp.currency': 'Currency',
    'bp.monthlyEstimate': 'Monthly estimate:',
    'bp.continue': 'Continue',
    'bp.back': 'Back',
    'bp.fixedTitle': 'Monthly fixed expenses',
    'bp.expenseName': 'Expense name',
    'bp.addExpense': 'Add expense',
    'bp.totalFixed': 'Total fixed expenses:',
    'bp.available': 'Available after fixed expenses:',
    'bp.planTitle': 'Choose your distribution plan',
    'bp.resultTitle': 'Plan result',
    'bp.plan': 'Plan',
    'bp.monthlyIncome': 'Monthly income',
    'bp.distributed': 'Distributed',
    'bp.unassigned': 'Unassigned',
    'bp.fixed': 'Fixed Expenses',
    'bp.recreation': 'Recreation',
    'bp.savings': 'Savings',
    'bp.remaining': 'Remaining',
    'bp.realExpenses': 'Real expenses',
    'bp.canSpend': 'You can spend more',
    'bp.exceeding': 'Exceeding by',
    'bp.reset': 'Reset plan',
    'bp.flexible': 'Flexible',
    'bp.flexibleDesc': 'You decide how much goes to recreation and savings.',
    'bp.moderate': 'Moderate',
    'bp.moderateDesc': '60% fixed, 25% recreation, 15% savings.',
    'bp.saver': 'Saver',
    'bp.saverDesc': '40% fixed, 30% recreation, 30% savings.',
    'bp.conservative': 'Conservative',
    'bp.conservativeDesc': '70% fixed, 20% recreation, 10% savings.',
    'bp.ambitious': 'Ambitious',
    'bp.ambitiousDesc': '45% fixed, 25% recreation, 30% savings.',
    'bp.balanced': 'Balanced',
    'bp.balancedDesc': 'One third for each category.',
    'bp.monthCycleTitle': 'Monthly Budget Cycle',
    'bp.cycleDay': 'Monthly cutoff day',
    'bp.currentMonth': 'Current month:',
    'bp.nextBudgetDate': 'Renewal date',
    'bp.monthStatus': 'Month status:',
    'bp.statusApplied': 'Applied',
    'bp.statusPending': 'Pending',
    'bp.prevCarryOver': 'Carry-over from previous month:',
    'bp.effectiveIncome': 'Effective monthly income:',
    'bp.pendingMonthSetup': 'Jarvis: this month has no applied budget yet. Complete the steps and apply your monthly budget.',
    'bp.applyMonthBudget': 'Apply monthly budget',
    'bp.updateMonthBudget': 'Update monthly budget',
    'bp.monthHistory': 'Monthly budget history',
    'bp.noMonthHistory': 'No monthly budgets applied yet.',

    // ── Navbar Spanish keys → English ─────────────────────────────────
    'Diario': 'Journal',
    'Rev. Semanal': 'Weekly Review',
    'Configuración': 'Settings',
    'Estadísticas': 'Statistics',
    'Identidad': 'Identity',
    'Historial': 'History',
    'Metas': 'Goals',
    'Stats': 'Statistics',
    'Salud Financiera': 'Financial Health',
    'Saldo Libre': 'Free Balance',
    'Hábitos — últimos 7 días': 'Habits — last 7 days',
    'Saludable': 'Healthy',
    'Atención': 'Attention',
    'Crítico': 'Critical',
    'Jarvis — Último análisis': 'Jarvis — Latest analysis',
    'Mostrar diagnóstico de agentes en el Omnibar': 'Show agent diagnostics in Omnibar',

    // ── Finance Spanish keys → English ────────────────────────────────
    'Próximos 7 días': 'Next 7 days',
    'Total mensual': 'Monthly Total',
    'Pagos recurrentes': 'Recurring Payments',

    // ── PersonalHub / DailyCheckin Spanish keys → English ─────────────
    'Captura rápida': 'Quick Capture',
    'Rutinas diarias': 'Daily Routines',
    'Nueva rutina': 'New routine',
    'Check-in diario': 'Daily Check-in',
    'Estado de ánimo': 'Mood',
    'Energía': 'Energy',
    'Horas de sueño': 'Sleep hours',
    'Nota rápida': 'Quick note',
    'Guardar check-in': 'Save check-in',
    '✓ Guardado': '✓ Saved',
    'Sin rutinas hoy.': 'No routines today.',
    'Sin rutinas aún.': 'No routines yet.',

    // ── WorkHub Spanish keys → English ────────────────────────────────
    'Crear tarea prioritaria': 'Create priority task',
    'Nueva tarea': 'New task',
    'Sin proyectos activos.': 'No active projects.',
    'Enfoque de hoy': "Today's Focus",

    // ── Common Spanish keys → English ─────────────────────────────────
    'Agregar': 'Add',
    'Eliminar': 'Delete',
    'Guardar': 'Save',
    'Cancelar': 'Cancel',
    'Editar': 'Edit',
    'Ver': 'View',
    'Monto': 'Amount',
    'Detalles opcionales': 'Optional details',
    'Ir a Calendario': 'Go to Calendar',
    'Ir a Notas': 'Go to Notes',
    'Ir a Pendientes': 'Go to Todos',
    'Ir a Pagos': 'Go to Payments',
    'Ir a Mis Tareas': 'Go to My Tasks',
    'Ir a Proyectos': 'Go to Projects',
    'Ir a Colaboradores': 'Go to Collaborators',
    'Marcar': 'Mark',
    'Hecho': 'Done',
    'Activo': 'Active',
    'Activa': 'Active',
    'En progreso': 'In Progress',
    'Completado': 'Completed',
    'Pendiente': 'Pending',
    'Notas Personales': 'Personal Notes',
    'Notas recientes': 'Recent Notes',
    'Pendientes activos': 'Pending Todos',
    'Recordatorios próximos': 'Upcoming Reminders',
    'Pagos próximos': 'Upcoming Payments',
    'Presupuesto mensual': 'Monthly Budget',
    'Historial mensual': 'Monthly History',
    'Gastos recientes': 'Recent Expenses',
    'Sin tareas aún.': 'No tasks yet.',
    'Sin notas aún.': 'No notes yet.',
    'Sin pendientes aún.': 'No todos yet.',
    'Sin pagos aún.': 'No payments yet.',
    'Sin gastos aún.': 'No expenses yet.',
    'Sin categorías aún.': 'No categories yet.'
  }
};

const LanguageContext = createContext({
  language: DEFAULT_LANGUAGE,
  setLanguage: () => {},
  toggleLanguage: () => {},
  t: (key) => key
});

const getStoredLanguage = () => {
  if (typeof window === 'undefined') return DEFAULT_LANGUAGE;
  try {
    const stored = window.localStorage.getItem(LANGUAGE_STORAGE_KEY);
    // Force English as default, only accept if explicitly set to 'es'
    return stored === 'es' ? 'es' : DEFAULT_LANGUAGE;
  } catch (error) {
    return DEFAULT_LANGUAGE;
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(getStoredLanguage);

  useEffect(() => {
    if (typeof window === 'undefined') return;
    try {
      window.localStorage.setItem(LANGUAGE_STORAGE_KEY, language);
    } catch (error) {
      // Ignore storage errors.
    }
  }, [language]);

  const value = useMemo(() => {
    const dictionary = translations[language] || {};
    const t = (key) => dictionary[key] || key;
    const toggleLanguage = () => setLanguage((prev) => (prev === 'es' ? 'en' : 'es'));
    return { language, setLanguage, toggleLanguage, t };
  }, [language]);

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
